"""Push / status / pull / verify the geometry_final job on the single allocated account.

    py -m geometry_final.kaggle push --tag pilot
    py -m geometry_final.kaggle push --tag main
    py -m geometry_final.kaggle status --tag main
    py -m geometry_final.kaggle pull --tag main
    py -m geometry_final.kaggle verify --tag main

Account ``maxmonstre`` only.  Inputs: its existing dataset ``landscape-v3-inputs``
(unchanged; digests rechecked inside the job) and the public CIFAR-10 python
batches.  The code (continuation_core, landscape_study, landscape_v2, landscape_v3,
geometry_final) and ``tasks.json`` travel inside the kernel script.  ``verify``
recomputes the sha256 of every file listed in ``manifest.json``; a client polling
timeout or a downloader exit code is never taken as evidence of anything.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import zipfile
from datetime import datetime, timezone

from landscape_v2.kaggle import env_for, run

from . import common as C

STAGE = C.STUDY / "kaggle_stage"

WRAPPER = '''# generated by geometry_final/kaggle.py
import base64, io, os, subprocess, sys, zipfile
repo = "/kaggle/working/_repo"
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
args = [sys.executable, "-m", "geometry_final.job", "--tasks", os.path.join(repo, "tasks.json"),
        "--out", "/kaggle/working/gf", "--deadline-hours", "{hours}"] + {extra}
r = subprocess.run(args, cwd=repo)
sys.exit(r.returncode)
'''


def kid(tag):
    return "%s/%s-%s" % (env_for(C.ACCOUNT)[1], C.KERNEL_SLUG, tag)


def payload():
    buf = io.BytesIO()
    files = []
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "landscape_study", "landscape_v2", "landscape_v3", "geometry_final"):
            for p in sorted((C.ROOT / pkg).rglob("*.py")):
                rel = p.relative_to(C.ROOT).as_posix()
                zf.write(p, rel)
                files.append({"path": rel, "sha256": hashlib.sha256(p.read_bytes()).hexdigest()})
        tasks = (C.PROTO / "tasks.json").read_bytes()
        zf.writestr("tasks.json", tasks)
        files.append({"path": "tasks.json", "sha256": hashlib.sha256(tasks).hexdigest()})
    return base64.b64encode(buf.getvalue()).decode("ascii"), files


def push(tag, hours):
    env, user = env_for(C.ACCOUNT)
    d = STAGE / ("kernel_" + tag)
    d.mkdir(parents=True, exist_ok=True)
    extra = '["--pilot"]' if tag == "pilot" else "[]"
    b64, files = payload()
    (d / "script.py").write_text(WRAPPER.format(payload=b64, hours=hours, extra=extra), encoding="utf-8")
    (d / "kernel-metadata.json").write_text(json.dumps({
        "id": kid(tag), "title": "%s-%s" % (C.KERNEL_SLUG, tag), "code_file": "script.py",
        "language": "python", "kernel_type": "script", "is_private": True, "enable_gpu": True,
        "enable_internet": False, "enable_tpu": False, "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": ["pankrzysiu/cifar10-python", C.INPUT_DATASET],
        "kernel_sources": [], "competition_sources": []}, indent=2))
    C.RAW.mkdir(parents=True, exist_ok=True)
    (C.RAW / ("launch_%s.json" % tag)).write_text(json.dumps(
        {"account": C.ACCOUNT, "kernel": kid(tag), "tag": tag, "launched_utc": datetime.now(timezone.utc).isoformat(),
         "script_sha256": hashlib.sha256((d / "script.py").read_bytes()).hexdigest(),
         "payload_files": files, "deadline_hours": hours}, indent=1))
    if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
        raise SystemExit("push failed")


def verify(tag):
    root = C.RAW / tag / "gf"
    rep = {"tag": tag}
    p = root / "manifest.json"
    if not p.exists():
        rep["manifest"] = "MISSING"
    else:
        listed = json.loads(p.read_text())
        missing, bad = [], []
        for rel, info in listed.items():
            f = root / rel
            if not f.exists():
                missing.append(rel)
            elif hashlib.sha256(f.read_bytes()).hexdigest() != info["sha256"] or f.stat().st_size != info["bytes"]:
                bad.append(rel)
        rep["manifest"] = {"listed": len(listed), "missing": missing, "hash_mismatch": bad}
    for name in ("environment.json", "COMPLETE.json", "timing.json"):
        q = root / name
        rep[name] = json.loads(q.read_text()) if q.exists() else "MISSING"
    rows = {}
    for sd in ("trace", "grid"):
        for f in sorted((root / sd).glob("*.jsonl")) if (root / sd).exists() else []:
            rows[f.relative_to(root).as_posix()] = sum(1 for line in f.read_text().splitlines() if line.strip())
    rep["jsonl_rows"] = rows
    (C.RAW / ("verify_%s.json" % tag)).write_text(json.dumps(rep, indent=1))
    print(json.dumps({k: v for k, v in rep.items() if k != "jsonl_rows"}, indent=1)[:3000])
    return rep


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("action", choices=("push", "status", "pull", "verify"))
    ap.add_argument("--tag", required=True)
    ap.add_argument("--hours", default="11.0")
    a = ap.parse_args()
    env = env_for(C.ACCOUNT)[0]
    if a.action == "push":
        push(a.tag, a.hours)
    elif a.action == "status":
        run(["kaggle", "kernels", "status", kid(a.tag)], env)
    elif a.action == "pull":
        dest = C.RAW / a.tag
        dest.mkdir(parents=True, exist_ok=True)
        run(["kaggle", "kernels", "output", kid(a.tag), "-p", str(dest), "-o"], env)
    else:
        verify(a.tag)


if __name__ == "__main__":
    main()
