"""Publish inputs, push the four jobs, pull and verify outputs.

    py -m landscape_v2.kaggle publish
    py -m landscape_v2.kaggle push [--accounts ...]
    py -m landscape_v2.kaggle status
    py -m landscape_v2.kaggle pull --account maxnicaise
    py -m landscape_v2.kaggle verify --account maxnicaise

Each account gets a private dataset ``landscape-v2-inputs`` (flat: assets,
subsets, preregistration, manifest) and one private T4 kernel
``landscape-v2-<account>`` that trains and evaluates the seeds assigned in
``common.ACCOUNT_SEEDS``.  ``verify`` recomputes the sha256 of every downloaded
file listed in the job's ``runs_manifest.json`` / ``eval_manifest.json`` and
reports missing, extra and mismatching files; a zero exit code of the CLI is not
taken as evidence.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import os
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from . import common as C

INPUTS = C.STUDY / "inputs"
STAGE = C.STUDY / "kaggle_stage"
RAW = C.STUDY / "raw"
SLUG = "landscape-v2-inputs"

WRAPPER = '''# generated by landscape_v2/kaggle.py
import base64, io, os, subprocess, sys, zipfile
repo = "/kaggle/working/_repo"
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
r = subprocess.run([sys.executable, "-m", "landscape_v2.run", "--stage", "all", "--seeds", {seeds},
                    "--out", "/kaggle/working/v2", "--deadline-hours", "{hours}"], cwd=repo)
sys.exit(r.returncode)
'''


def env_for(acc):
    cfg = Path.home() / ".kaggle-accounts" / acc
    return ({**os.environ, "KAGGLE_CONFIG_DIR": str(cfg)},
            json.loads((cfg / "kaggle.json").read_text())["username"])


def run(cmd, env):
    print("$ " + " ".join(cmd), flush=True)
    r = subprocess.run([shutil.which("kaggle") or "kaggle"] + cmd[1:], text=True, capture_output=True,
                       env=env, encoding="utf-8", errors="replace")
    print(((r.stdout or "") + (r.stderr or ""))[-3000:], flush=True)
    return r


def publish(accounts):
    if STAGE.exists():
        shutil.rmtree(STAGE)
    STAGE.mkdir(parents=True)
    for p in (INPUTS / "assets").iterdir():
        shutil.copy2(p, STAGE / p.name)
    for n in ("subsets.npz", "preregistration.json", "manifest.json"):
        shutil.copy2(INPUTS / n, STAGE / n)
    for acc in accounts:
        env, user = env_for(acc)
        (STAGE / "dataset-metadata.json").write_text(json.dumps(
            {"title": "landscape v2 inputs", "id": "%s/%s" % (user, SLUG), "licenses": [{"name": "unknown"}]}))
        if run(["kaggle", "datasets", "create", "-p", str(STAGE)], env).returncode:
            raise SystemExit("publish failed for %s" % acc)


def payload():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "landscape_study", "landscape_v2"):
            for p in sorted((C.ROOT / pkg).rglob("*.py")):
                zf.write(p, p.relative_to(C.ROOT).as_posix())
    return base64.b64encode(buf.getvalue()).decode("ascii")


def kid(acc):
    return "%s/landscape-v2-%s" % (env_for(acc)[1], acc.lower())


def push(accounts, hours):
    for acc in accounts:
        env, user = env_for(acc)
        d = STAGE.parent / ("kernel_%s" % acc)
        d.mkdir(parents=True, exist_ok=True)
        seeds = ", ".join('"%d"' % s for s in C.ACCOUNT_SEEDS[acc])
        (d / "script.py").write_text(WRAPPER.format(payload=payload(), seeds=seeds, hours=hours), encoding="utf-8")
        (d / "kernel-metadata.json").write_text(json.dumps({
            "id": kid(acc), "title": "landscape-v2-%s" % acc.lower(), "code_file": "script.py",
            "language": "python", "kernel_type": "script", "is_private": True, "enable_gpu": True,
            "enable_internet": False, "enable_tpu": False, "machine_shape": "NvidiaTeslaT4",
            "dataset_sources": ["pankrzysiu/cifar10-python", "%s/%s" % (user, SLUG)],
            "kernel_sources": [], "competition_sources": []}, indent=2))
        RAW.mkdir(parents=True, exist_ok=True)
        (RAW / ("launch_%s.json" % acc)).write_text(json.dumps(
            {"account": acc, "kernel": kid(acc), "seeds": C.ACCOUNT_SEEDS[acc],
             "launched_utc": datetime.now(timezone.utc).isoformat()}, indent=2))
        if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
            raise SystemExit("push failed for %s" % acc)


def verify(acc):
    import hashlib
    root = RAW / acc / "v2"
    rep = {"account": acc}
    for man in ("runs_manifest.json", "eval_manifest.json"):
        p = root / man
        if not p.exists():
            rep[man] = "MISSING MANIFEST"
            continue
        listed = json.loads(p.read_text())
        missing, bad = [], []
        for rel, info in listed.items():
            f = root / rel
            if not f.exists():
                missing.append(rel)
                continue
            h = hashlib.sha256(f.read_bytes()).hexdigest()
            if h != info["sha256"] or f.stat().st_size != info["bytes"]:
                bad.append(rel)
        rep[man] = {"listed": len(listed), "missing": missing, "hash_mismatch": bad}
    (RAW / ("verify_%s.json" % acc)).write_text(json.dumps(rep, indent=2))
    print(json.dumps({k: (v if isinstance(v, str) else {kk: (len(vv) if isinstance(vv, list) else vv)
                                                         for kk, vv in v.items()}) if k != "account" else v
                      for k, v in rep.items()}, indent=1))
    return rep


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("action", choices=("publish", "push", "status", "pull", "verify"))
    ap.add_argument("--accounts", nargs="*", default=list(C.ACCOUNT_SEEDS))
    ap.add_argument("--account")
    ap.add_argument("--hours", default="11.2")
    a = ap.parse_args()
    accs = [a.account] if a.account else a.accounts
    if a.action == "publish":
        publish(accs)
    elif a.action == "push":
        push(accs, a.hours)
    elif a.action == "status":
        for acc in accs:
            run(["kaggle", "kernels", "status", kid(acc)], env_for(acc)[0])
    elif a.action == "pull":
        for acc in accs:
            (RAW / acc).mkdir(parents=True, exist_ok=True)
            run(["kaggle", "kernels", "output", kid(acc), "-p", str(RAW / acc)], env_for(acc)[0])
    else:
        for acc in accs:
            verify(acc)


if __name__ == "__main__":
    main()
