"""Build the standalone exploration catalogue from the audited configuration records.

    py paper/tools/build_catalogue.py

Reads ``data/records/catalogue_configurations.csv`` and ``catalogue_cells.csv``
(written by ``build_records.py`` from the original run summaries) and writes, into
``catalogue/``:

    exploration_catalogue.csv   one row per configuration, machine-readable
    exploration_catalogue.tex   the same rows as a standalone document
    exploration_catalogue.md    a readable text version with the group headers
    CHANGE_LOG.md               corrections applied to the historical values

Every configuration of the supplied catalogue is kept, including configurations
whose runs diverged and separate launches of the same configuration.  The generic
endpoint field of the original table is not reproduced: it is unreliable for the
early fixed-input-blur pilots, and the true inference state is given per
experiment instead.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

PAPER = Path(__file__).resolve().parents[1]
REC = PAPER / "data" / "records"
OUT = PAPER / "catalogue"

ORDER = ["unified_selected", "resbench_resolution_only", "campaign_grid21", "ablation_aa",
         "per_layer_sigma", "adaptive_continuation", "fulldata_gaussian",
         "progressive_resolution_pilot", "resnet20bn_gaussian_pilot",
         "resnet18bn_gaussian_pilot", "db2_pilot", "gn_lr_audit", "pilot_internal_gaussian",
         "exp0_input_gaussian", "exp1_input_warmstart"]

TEX_HEAD = r"""\documentclass[10pt]{article}
\usepackage[a4paper,margin=2cm]{geometry}
\usepackage[T1]{fontenc}
\usepackage{booktabs,longtable,array,lmodern}
\usepackage[hidelinks]{hyperref}
\setlength{\tabcolsep}{4pt}
\begin{document}
\title{Exploration catalogue: every trained configuration of the CIFAR-10 study}
\author{Companion record to \emph{Continuation Methods for Training Convolutional Neural
Networks}}
\date{Generated by \texttt{paper/tools/build\_catalogue.py} from the run records}
\maketitle

This catalogue lists every configuration trained during the CIFAR-10 exploration that
precedes the selection of the three procedures, grouped by experiment.  It is a
traceability record, not a ranking: the experiments differ in data, budget, evaluation
split and inference state, and are therefore not comparable across groups.  Accuracy is
the final recorded evaluation of each run, averaged over the numerically valid seeds,
with no best-epoch selection; SD is the sample standard deviation over those seeds and is
absent when a single seed is valid.  Seeds are reported as valid/attempted, so diverged
runs remain visible.  Wall time is the mean over valid runs, on the timing scope stated in
each group header.

Every value here was recomputed from the per-run \texttt{summary.json} records; see
\texttt{CHANGE\_LOG.md}.

"""

TEX_TABLE = r"""\begingroup\small
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{9.2cm}rrcr@{}}
\toprule Configuration & Acc.\ (\%) & SD & Seeds & Wall (s)\\\midrule
\endfirsthead
\toprule Configuration & Acc.\ (\%) & SD & Seeds & Wall (s)\\\midrule
\endhead
\midrule\multicolumn{5}{r@{}}{\emph{continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
"""

_UNI = {"→": "$\\to$", "—": "---", "–": "--", "×": "$\\times$",
        "σ": "$\\sigma$", "−": "$-$", "≈": "$\\approx$"}


def tex(s) -> str:
    s = str(s).replace("H^-1", "\x01HM\x01").replace("\\", "\\textbackslash{}")
    for a, b in (("&", "\\&"), ("%", "\\%"), ("$", "\\$"), ("#", "\\#"), ("_", "\\_"),
                 ("{", "\\{"), ("}", "\\}"), ("~", "\\textasciitilde{}"),
                 ("^", "\\textasciicircum{}")):
        s = s.replace(a, b)
    s = s.replace("\\textbackslash\\{\\}", "\\textbackslash{}")
    for a, b in _UNI.items():
        s = s.replace(a, b)
    return s.replace("\x01HM\x01", "$H^{-1}$")


def num(v, digits=2):
    return "---" if pd.isna(v) else ("%." + str(digits) + "f") % v


def main():
    cfg = pd.read_csv(REC / "catalogue_configurations.csv")
    cells = pd.read_csv(REC / "catalogue_cells.csv")
    OUT.mkdir(parents=True, exist_ok=True)

    cfg = cfg.assign(_order=[ORDER.index(e) if e in ORDER else len(ORDER) for e in cfg.experiment])
    cfg = cfg.sort_values(["_order", "label"]).drop(columns="_order")
    cfg.to_csv(OUT / "exploration_catalogue.csv", index=False)

    tex_rows, md_rows = [], ["# Exploration catalogue", "",
                             "Every trained configuration of the CIFAR-10 exploration, grouped by "
                             "experiment, recomputed from the per-run records. Accuracy is the "
                             "final recorded evaluation, averaged over valid seeds; seeds are "
                             "valid/attempted.", ""]
    for eid in ORDER:
        g = cfg[cfg.experiment == eid]
        if g.empty:
            continue
        head = g.iloc[0]
        info = ("%s (%s; owner %s). Conditions: %s. Evaluation split: %s. Timing: %s."
                % (head.experiment_title, eid, head.owner, str(head.conditions).rstrip("."),
                   head.evaluation_split or "n/a", head.timing_scope))
        tex_rows.append(r"\multicolumn{5}{@{}p{\linewidth}@{}}{\rule{0pt}{2.8ex}\textbf{%s}}\\*"
                        % tex(head.experiment_title))
        tex_rows.append(r"\multicolumn{5}{@{}p{\linewidth}@{}}{\footnotesize %s}\\*" % tex(info))
        md_rows += ["## %s" % head.experiment_title, "", info, "",
                    "| Configuration | Acc. (%) | SD | Seeds | Wall (s) |", "|---|---|---|---|---|"]
        for r in g.itertuples():
            label = r.label
            if r.status != "valid":
                label += " (diverged)"
            if isinstance(r.flags, str) and r.flags:
                label += " (%s)" % r.flags.replace(";", ", ")
            seeds = "%d/%d" % (r.seeds_valid, r.seeds_attempted)
            tex_rows.append("%s & %s & %s & %s & %s\\\\" % (
                tex(label), num(r.acc_mean), num(r.acc_sd), seeds,
                "---" if pd.isna(r.wall_seconds_mean) else "%.0f" % r.wall_seconds_mean))
            md_rows.append("| %s | %s | %s | %s | %s |" % (
                label, num(r.acc_mean), num(r.acc_sd), seeds,
                "---" if pd.isna(r.wall_seconds_mean) else "%.0f" % r.wall_seconds_mean))
        md_rows.append("")

    (OUT / "exploration_catalogue.tex").write_text(
        TEX_HEAD + TEX_TABLE + "\n".join(tex_rows) + "\n" + r"\end{longtable}\endgroup" + "\n"
        + r"\end{document}" + "\n", encoding="utf-8")
    (OUT / "exploration_catalogue.md").write_text("\n".join(md_rows), encoding="utf-8")

    changed = cfg[(cfg.index_acc_mean.notna())
                  & ((cfg.acc_mean - cfg.index_acc_mean).abs() > 5e-3)]
    log = ["# Change log", "",
           "Values recomputed from the per-run `summary.json` records of every cell, using the "
           "configuration membership recorded in the experiment index.", "",
           "- configurations: %d" % len(cfg),
           "- runs behind them: %d (numerically valid: %d)" % (len(cells), int(cells.valid.sum())),
           "- configurations whose recomputed accuracy differs from the supplied index: %d"
           % len(changed), ""]
    if len(changed):
        log += ["| configuration | supplied | recomputed |", "|---|---|---|"]
        log += ["| %s/%s | %.2f | %.2f |" % (r.experiment, r.config_id, r.index_acc_mean,
                                             r.acc_mean) for r in changed.itertuples()]
    else:
        log.append("No corrections were needed: every configuration reproduces the supplied value.")
    log += ["", "The generic `Endpoint=target` column of the original table is deliberately not "
            "reproduced; it is unreliable for the early fixed-input-blur pilots. The inference "
            "state of each study is stated in its group header instead.", ""]
    (OUT / "CHANGE_LOG.md").write_text("\n".join(log), encoding="utf-8")

    print("catalogue: %d configurations, %d runs" % (len(cfg), len(cells)))
    print("wrote catalogue/exploration_catalogue.{csv,tex,md} and CHANGE_LOG.md")


if __name__ == "__main__":
    main()
