"""Stage 2 of the asset pipeline: tidy records -> tables, figures and prose macros.

    py paper/tools/build_assets.py

Reads only ``data/records/*.csv`` (written by ``build_records.py`` from the original
experiment records) and writes ``tables/*.tex``, ``tables/numbers_generated.tex``,
``figures/*.pdf`` with a ``.png`` preview, and ``evidence/RECOMPUTED_CHECKS.json``.
Nothing here loads a network, trains or evaluates a model.

Conventions of every table and figure written here:

* a value is the final scheduled epoch of a run, never a best-epoch selection;
* ``mean +/- SD`` is the mean and the sample standard deviation across *training
  seeds* of one setting; it is not a confidence interval, and it is absent when a
  setting has a single seed;
* paired gains and paired differences are formed within a seed and averaged
  afterwards; repeated perturbation directions are not replications;
* units are named in the column header: percent, percentage points, nats, minutes;
* a fact shared by every row of a block is printed once in the block heading, and a
  fact that varies is printed in the row, so no row depends on a distant reference.
"""
from __future__ import annotations

import io
import json
import os
import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.colors import Normalize  # noqa: E402

PAPER = Path(__file__).resolve().parents[1]
REC = PAPER / "data" / "records"
TAB = PAPER / "tables"
FIG = PAPER / "figures"

M = ["plain", "resolution_max_b1", "gaussian_postrelu", "resolution_max_b1_gaussian_conv"]
NAME = dict(zip(M, ["Plain", "R", "G", "RG"]))
LONG = dict(zip(M, ["Plain", "Resolution", "Gaussian", "Combined"]))
COLOR = dict(zip(M, ["#333333", "#1976b2", "#dc7b13", "#8653aa"]))
POLICY = {"saved": "Saved statistics", "centre_frozen": "Centre-frozen statistics",
          "recalibrated": "Recalibrated at every point"}
POLICY_SHORT = {"saved": "Saved", "centre_frozen": "Centre-frozen", "recalibrated": "Pointwise"}

plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 9, "axes.labelsize": 9,
                     "axes.titlesize": 9.5, "legend.fontsize": 8, "pdf.fonttype": 42,
                     "ps.fonttype": 42, "axes.spines.top": False, "axes.spines.right": False})


def rec(name: str) -> pd.DataFrame:
    return pd.read_csv(REC / (name + ".csv"))


def save(fig, name: str):
    FIG.mkdir(parents=True, exist_ok=True)
    for fmt in ("pdf", "png"):
        buf = io.BytesIO()
        fig.savefig(buf, format=fmt, dpi=180, bbox_inches="tight")
        payload = buf.getvalue()
        buf.close()
        dst = FIG / ("%s.%s" % (name, fmt))
        tmp = dst.with_suffix(".%s.tmp" % fmt)
        with open(tmp, "wb") as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        tmp.replace(dst)
    plt.close(fig)
    print("wrote figures/%s.pdf (+png)" % name)


def tex(name: str, body: str):
    TAB.mkdir(parents=True, exist_ok=True)
    head = ("% GENERATED by paper/tools/build_assets.py from data/records/ -- do not edit by hand.\n"
            "% Regenerate: py paper/tools/build_records.py && py paper/tools/build_assets.py\n")
    (TAB / (name + ".tex")).write_text(head + body.strip() + "\n", encoding="utf-8")
    print("wrote tables/%s.tex" % name)


def pm(a, b, d=2, sign=False):
    if pd.isna(a):
        return "---"
    if pd.isna(b):
        return ("$%+.*f$" if sign else "$%.*f$") % (d, a)
    return ("$%+.*f\\pm%.*f$" if sign else "$%.*f\\pm%.*f$") % (d, a, d, b)


def thousands(v) -> str:
    return "{:,}".format(int(round(float(v)))).replace(",", "\\,")


def sig(a, b, digits=3) -> str:
    """Mean and SD to a fixed number of significant digits of the mean.

    Training-probe cross-entropies span four orders of magnitude between settings, so a
    fixed number of decimals would print several of them as zero.
    """
    if pd.isna(a):
        return "---"
    exp = 0 if a == 0 else int(np.floor(np.log10(abs(a))))
    d = max(0, digits - 1 - exp)
    return "$%.*f\\pm%.*f$" % (d, a, d, 0 if pd.isna(b) else b)


# --------------------------------------------------------------------- benchmark tables

#: (block heading: the facts every row of the block shares, [(row label: what varies, setting)])
BLOCKS = [
    ("CIFAR-10, 50\\,000 training and 10\\,000 test images; ResNet-20-BN / ReLU; "
     "30 epochs $\\times$ 391 updates; the optimizer varies",
     [("SGD, $\\eta=0.005$ (the selection batch)", "sgd"),
      ("Adam, $\\eta=0.003$", "adam"),
      ("AdamW, $\\eta=0.02$", "adamw"),
      ("RAdam, $\\eta=0.003$", "radam")]),
    ("CIFAR-10, 50\\,000 training and 10\\,000 test images; SGD, $\\eta=0.005$; "
     "30 epochs $\\times$ 391 updates; the model varies",
     [("ResNet-20-BN / GELU", "resnet20act_cifar10/gelu"),
      ("ResNet-20-BN / SiLU", "resnet20act_cifar10/silu"),
      ("ResNet-20-GN(8) / ReLU", "resnet20gn_cifar10"),
      ("VGG-11-BN / ReLU", "vgg11_cifar10")]),
    ("SVHN, 50\\,000 of the 73\\,257 training and 26\\,032 test images; ResNet-20-BN / ReLU; "
     "SGD, $\\eta=0.005$",
     [("30 epochs $\\times$ 391 updates", "svhn")]),
    ("STL-10, 5\\,000 training and 8\\,000 test images at $96\\times96$; ResNet-20-BN / ReLU; "
     "SGD, $\\eta=0.005$",
     [("60 epochs $\\times$ 40 updates", "stl10")]),
    ("CIFAR-10 subset, the same 5\\,000 training and 10\\,000 test images; ResNet-20-BN / ReLU; "
     "SGD, $\\eta=0.005$; the budget varies",
     [("60 epochs $\\times$ 40 updates", "cifar10_5k/stl_budget"),
      ("293 epochs $\\times$ 40 updates", "cifar10_5k/reference_updates")]),
]


def blocks_body(row_fn, ncols, keep=None):
    out = []
    for title, rows in BLOCKS:
        rows = [(lab, st) for lab, st in rows if keep is None or st in keep]
        if not rows:
            continue
        out.append("\\multicolumn{%d}{@{}p{\\linewidth}@{}}{\\rule{0pt}{2.6ex}\\textit{%s}}\\\\"
                   % (ncols, title))
        out += [row_fn(lab, st) for lab, st in rows]
        out.append("\\addlinespace[3pt]")
    return "\n".join(out[:-1])


def benchmark_tables(S: pd.DataFrame):
    def g_of(st):
        return S[S.setting == st].set_index("method")

    def acc_row(label, st):
        g = g_of(st)
        return "\\quad %s & %s\\\\" % (
            label, " & ".join(pm(g.loc[m].test_acc_mean, g.loc[m].test_acc_sd) for m in M))

    tex("transfer_main", r"""\begin{table*}[t]
\caption{Final test accuracy (\%), mean $\pm$ sample SD across the three training seeds of each
setting. A block heading gives the data, model, optimizer and budget shared by its rows, and the row
gives the one field that varies; every setting trains the same four procedures, at the scheduled
endpoint, with no augmentation and no best-epoch selection. R: temporary resolution reduction; G:
Gaussian filtering of feature maps; RG: their combination (Table~\ref{tab:methods}). Learning rates
for the adaptive optimizers were selected on plain, seed 0, by test accuracy; SGD keeps the
exploratory rate. The SGD row is the original selection batch, reused here, not a new replication.
Within-seed gains over plain are in Table~\ref{tab:transfer-paired}, the remaining recipe details in
Table~\ref{tab:transfer-protocol}.}
\label{tab:transfer}
\centering\small
\begin{tabular}{@{}lcccc@{}}
\toprule
Setting & \multicolumn{4}{c@{}}{Final test accuracy (\%)}\\
\cmidrule(l){2-5}
 & Plain & R & G & RG\\
\midrule
""" + blocks_body(acc_row, 5) + r"""
\bottomrule
\end{tabular}
\end{table*}""")

    def gain_row(label, st):
        g = g_of(st)
        return "\\quad %s & %s\\\\" % (
            label, " & ".join("%s (%d/%d)" % (pm(g.loc[m].gain_mean, g.loc[m].gain_sd, sign=True),
                                              int(g.loc[m].n_seeds_gain_positive),
                                              int(g.loc[m].n_seeds)) for m in M[1:]))

    tex("transfer_paired", r"""\begin{table}[!htbp]
\caption{Within-seed gain over plain in percentage points: the mean of the three per-seed
differences $\pm$ their sample SD, with the number of seeds whose difference is positive in
parentheses. Same runs, settings and endpoints as Table~\ref{tab:transfer}, and the same block
headings. A difference pairs a procedure with the plain run that shares its seed, initial weights
and data order inside one setting; differences are never taken across settings or batches, and the
SD of a gain is the SD of those differences, not of the accuracies.}
\label{tab:transfer-paired}
\centering\small
\begin{tabular}{@{}lccc@{}}
\toprule
Setting & \multicolumn{3}{c@{}}{Gain over plain (pp)}\\
\cmidrule(l){2-4}
 & $\Delta$ R & $\Delta$ G & $\Delta$ RG\\
\midrule
""" + blocks_body(gain_row, 4) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    have_ce = set(S[S.test_ce_mean.notna()].setting)

    def ce_row(label, st):
        g = g_of(st)
        r = g.loc["plain"]
        probe = "---" if pd.isna(r.train_probe_n) else thousands(r.train_probe_n)
        a = "\\quad %s & train probe, %s & %s\\\\" % (
            label, probe,
            " & ".join(sig(g.loc[m].train_probe_ce_mean, g.loc[m].train_probe_ce_sd) for m in M))
        b = "\\quad %s & test set, %s & %s\\\\" % (
            label, thousands(r.n_test),
            " & ".join(pm(g.loc[m].test_ce_mean, g.loc[m].test_ce_sd, 3) for m in M))
        return a + "\n" + b

    tex("transfer_ce", r"""\begin{table}[!htbp]
\caption{Final cross-entropy in nats, mean $\pm$ sample SD across three training seeds. Training
values are measured on that setting's fixed training probe, whose size is given in the second
column: they are probe measurements, not the cross-entropy of the complete training set. Test values
use the complete test set, whose size is also given. Values are printed to three significant digits
of the mean, since training cross-entropies span four orders of magnitude between settings. The
optimizer exports do not record endpoint cross-entropies, so those settings do not appear here.}
\label{tab:transfer-ce}
\centering\small
\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}Xlcccc@{}}
\toprule
Setting & Population & Plain & R & G & RG\\
\midrule
""" + blocks_body(ce_row, 6, keep=have_ce) + r"""
\bottomrule
\end{tabularx}
\end{table}""")

    def cost_row(label, st):
        g = g_of(st)
        return "\\quad %s & every %d ep. & %s\\\\" % (
            label, int(g.loc["plain"].eval_every_epochs),
            " & ".join(pm(g.loc[m].wall_minutes_mean, g.loc[m].wall_minutes_sd) for m in M))

    tex("costs", r"""\begin{table}[!htbp]
\caption{Measured total wall time in minutes: mean $\pm$ sample SD over the three runs of each cell,
computed from the recorded per-run times. The timer starts after data and model construction and
ends at the last evaluation, so it includes the evaluations, whose frequency is printed in the row,
and the checkpoint writes. Runs of different settings ran in different shared GPU sessions,
sometimes two cells per device, so times are comparable within a row and not between rows; this is
not a controlled hardware comparison. Within-seed ratios to plain are kept in
\texttt{data/records/benchmark\_settings.csv}.}
\label{tab:costs}
\centering\small
\begin{tabular}{@{}llcccc@{}}
\toprule
Setting & Evaluation & \multicolumn{4}{c@{}}{Total wall time (min)}\\
\cmidrule(l){3-6}
 & & Plain & R & G & RG\\
\midrule
""" + blocks_body(cost_row, 6) + r"""
\bottomrule
\end{tabular}
\end{table}""")


# --------------------------------------------------------------------- landscape tables

SET_LABEL = {"train_large": "Train 10\\,000", "test_full": "Test 10\\,000"}


def landscape_tables(large, large_paired, hess, endpoints):
    rows = []
    for pol in ("saved", "recalibrated"):
        for st in ("train_large", "test_full"):
            for amp in (0.1, 0.25):
                g = (large[(large.policy == pol) & (large.evaluation_set == st)
                           & (large.amplitude == amp)].groupby("method").S.agg(["mean", "std"]))
                rows.append("%s & %s & %g & %s\\\\" % (
                    POLICY_SHORT[pol], SET_LABEL[st], amp,
                    " & ".join(pm(g.loc[m]["mean"], g.loc[m]["std"], 3) for m in M)))
    tex("sensitivity_validation", r"""\begin{table}[!htbp]
\caption{Finite sensitivity $S$ of Equation~\eqref{eq:sensitivity}, in nats, on the larger
evaluation populations: mean $\pm$ sample SD across the five training seeds of the landscape batch,
after averaging the same 20 filter-normalized random directions and both signs inside each seed.
CIFAR-10, ResNet-20-BN with ReLU, SGD, the final 30-epoch checkpoints evaluated on the native
filter-free network. \emph{Train 10\,000} is the 10\,000-image training subset and \emph{Test
10\,000} the complete test set; \emph{Saved} freezes the checkpoint statistics and
\emph{Pointwise} recalibrates them at every perturbed point. $S$ is the rise of cross-entropy above
that model's own unperturbed loss under the same policy: neither an accuracy nor the unperturbed
loss, it may be negative and is not clipped. $\varepsilon$ is the relative displacement $r(\delta)$
of Appendix~\ref{app:landscape}. Paired differences are in
Table~\ref{tab:sensitivity-validation-paired}.}
\label{tab:sensitivity-validation}
\centering\small
\begin{tabular}{@{}llrcccc@{}}
\toprule
BatchNorm & Population & $\varepsilon$ & $S$: Plain & $S$: R & $S$: G & $S$: RG\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    rows = []
    for pol in ("saved", "recalibrated"):
        for st in ("train_large", "test_full"):
            for amp in (0.1, 0.25):
                g = large_paired[(large_paired.policy == pol)
                                 & (large_paired.evaluation_set == st)
                                 & (large_paired.amplitude == amp)].set_index("method")
                rows.append("%s & %s & %g & %s\\\\" % (
                    POLICY_SHORT[pol], SET_LABEL[st], amp,
                    " & ".join("%s (%d/%d)" % (
                        pm(g.loc[m].mean_delta, g.loc[m].sd_delta, 3, sign=True),
                        int(g.loc[m].n_seeds_below_plain), int(g.loc[m].n_seeds)) for m in M[1:])))
    tex("sensitivity_validation_paired", r"""\begin{table}[!htbp]
\caption{Paired sensitivity differences $\Delta S=S_{\rm method}-S_{\rm plain}$ in nats, for the
measurements of Table~\ref{tab:sensitivity-validation} and with the same labels: the difference is
formed inside each training seed and then averaged, and the SD is the sample SD of those five
per-seed differences. Parentheses count the seeds with a negative difference. Negative means a
smaller loss increase than plain, not a lower loss.}
\label{tab:sensitivity-validation-paired}
\centering\small
\begin{tabular}{@{}llrccc@{}}
\toprule
BatchNorm & Population & $\varepsilon$ & $\Delta S$: R & $\Delta S$: G & $\Delta S$: RG\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    rows = []
    for m in M[1:]:
        vals = []
        for probe in ("train_probe", "test_probe"):
            w = hess[(hess.policy == "centre_frozen") & (hess.coords == "relative")
                     & (hess.probe == probe)].pivot(index="seed", columns="method", values="top1")
            r = w[m] / w["plain"]
            vals.append(pm(r.mean(), r.std()))
        rows.append("%s & %s\\\\" % (LONG[m], " & ".join(vals)))
    tex("hessian_main", r"""\begin{table}[t]
\caption{Largest algebraic Hessian eigenvalue relative to the plain model of the same training
seed. CIFAR-10, ResNet-20-BN with ReLU, SGD, the five final 30-epoch checkpoints of the landscape
batch; mean cross-entropy without weight decay over the 268\,336 convolution and classifier
weights, on a 1\,000-image class-balanced probe, with BatchNorm recalibrated once at the
unperturbed weights and then held fixed, in block-relative coordinates $H_{\rm rel}=A^\top H A$.
Entries are the mean $\pm$ sample SD of the five within-seed ratios, so plain is 1 by construction;
the absolute eigenvalues, the other policy and the ordinary coordinates are in
Table~\ref{tab:hessian-all}. A ratio below 1 is a smaller leading curvature in these coordinates.}
\label{tab:hessian}
\centering\small
\begin{tabular}{@{}lcc@{}}
\toprule
Method & Train probe & Test probe\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    rows = []
    for pol in ("saved", "centre_frozen"):
        for coords in ("ordinary", "relative"):
            for probe in ("train_probe", "test_probe"):
                g = hess[(hess.policy == pol) & (hess.coords == coords) & (hess.probe == probe)]
                rows.append("%s & %s & %s & %s\\\\" % (
                    POLICY_SHORT[pol], coords, "Train" if probe == "train_probe" else "Test",
                    " & ".join(pm(g[g.method == m].top1.mean(), g[g.method == m].top1.std(), 0)
                               for m in M)))
    tex("hessian_all", r"""\begin{table}[!htbp]
\caption{Largest algebraic Hessian eigenvalue of the mean cross-entropy without weight decay, over
the 268\,336 convolution and classifier weights: mean $\pm$ sample SD across the five training
seeds of the landscape batch. CIFAR-10, ResNet-20-BN with ReLU, SGD, final 30-epoch checkpoints,
1\,000-image class-balanced probes. \emph{Saved} freezes the checkpoint statistics,
\emph{Centre-frozen} recalibrates them once at the unperturbed weights. Ordinary and block-relative
coordinates are different matrices: compare methods within a row, never eigenvalues between the two
coordinate groups.}
\label{tab:hessian-all}
\centering\small
\begin{tabular}{@{}lllrrrr@{}}
\toprule
BatchNorm & Coordinates & Probe & Plain & R & G & RG\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    g = endpoints.groupby("method")
    rows = ["%s & %s & %s & %s\\\\" % (
        LONG[m], pm(100 * g.get_group(m).test_full_acc.mean(),
                    100 * g.get_group(m).test_full_acc.std()),
        pm(g.get_group(m).train_full_ce.mean(), g.get_group(m).train_full_ce.std(), 3),
        pm(g.get_group(m).test_full_ce.mean(), g.get_group(m).test_full_ce.std(), 3)) for m in M]
    tex("landscape_endpoints", r"""\begin{table}[!htbp]
\caption{Endpoints of the twenty models of the landscape batch: CIFAR-10, ResNet-20-BN with ReLU,
SGD at the reference recipe, 30 epochs, five training seeds per method. Values are measured on the
native filter-free network with each checkpoint's own BatchNorm statistics, on the complete
50\,000-image training set and the complete 10\,000-image test set, as the mean $\pm$ sample SD
across the five seeds. This is a separate batch from the three-seed selection batch of
Table~\ref{tab:transfer} and is never pooled with it.}
\label{tab:landscape-endpoints}
\centering\small
\begin{tabular}{@{}lrrr@{}}
\toprule
Method & Test accuracy (\%) & Train CE (nats) & Test CE (nats)\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")


# --------------------------------------------------------------------- input diagnostics

VARIANT = [("reference", "Reference recipe"), ("lr_low", "$\\eta=0.0025$"),
           ("lr_high", "$\\eta=0.01$"), ("wd_low", "$w=10^{-4}$"),
           ("wd_high", "$w=2\\times10^{-3}$")]


def input_tables(cells):
    ref = cells[cells.recipe_variant == "reference"]
    rows = []
    for m in M:
        g = ref[ref.method == m]
        rows.append("%s & %s & %s & %s & %s\\\\" % (
            LONG[m], pm(100 * (1 - g.test_error).mean(), 100 * g.test_error.std()),
            pm(g.jac_frobenius.mean(), g.jac_frobenius.std(), 1),
            pm(g.jac_spectral.mean(), g.jac_spectral.std(), 1),
            pm(g.freq_mean_radius.mean(), g.freq_mean_radius.std())))
    tex("input_reference", r"""\begin{table}[!htbp]
\caption{Input-derivative diagnostics of the separate 28-run grid, reference group: CIFAR-10,
ResNet-20-BN with ReLU, SGD at the reference recipe, 30 epochs, three training seeds per method,
final checkpoints evaluated with their own BatchNorm statistics. $\|J\|_F$ and $\|J\|_2$ are the
Frobenius and spectral norms of the logit Jacobian $\partial f/\partial x$, in logits per unit image
intensity, averaged over the first 1\,000 images of the pinned training subset; the radius is the
energy-weighted spatial Fourier radius of that Jacobian, in cycles per image. Values are the mean
$\pm$ sample SD across the three seeds. This batch is neither the benchmark batch of
Table~\ref{tab:transfer} nor the landscape batch of Table~\ref{tab:landscape-endpoints}, and is
never pooled with them.}
\label{tab:input-reference}
\centering\small
\begin{tabular}{@{}lrrrr@{}}
\toprule
Method & Test accuracy (\%) & $\mathbb E\|J\|_F$ & $\mathbb E\|J\|_2$ & Mean radius (cycles/image)\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")

    rows = []
    for k, (variant, label) in enumerate(VARIANT):
        for m in M:
            g = cells[(cells.recipe_variant == variant) & (cells.method == m)]
            rows.append("%s & %s & %d & %.2f & %.3f & %.3f & %.1f & %s\\\\" % (
                label, LONG[m], len(g), 100 * (1 - g.test_error).mean(), g.train_ce.mean(),
                g.test_ce.mean(), g.jac_frobenius.mean(), thousands(g.trace_deflated.mean())))
        if k < len(VARIANT) - 1:
            rows.append("\\addlinespace[3pt]")
    tex("input_grid", r"""\begin{table}[!htbp]
\caption{All twenty method--recipe conditions of the separate input-derivative grid: CIFAR-10,
ResNet-20-BN with ReLU, SGD, 30 epochs, one change to the reference recipe per block ($\eta$ is the
learning rate and $w$ the weight decay; the reference uses $\eta=0.005$, $w=5\times10^{-4}$). $n$ is
the number of recorded training seeds: three in the reference block and one in every changed
recipe, so those rows carry no estimated between-seed SD and the reference SDs are in
Table~\ref{tab:input-reference}. Cross-entropies in nats are measured on the complete 50\,000-image
training set and the complete 10\,000-image test set. $\mathbb E\|J\|_F$ averages 1\,000 training
images. $\widehat{\mathrm{tr}}(H)$ is a stochastic Hutchinson estimate of the trace of the parameter
Hessian over all 269\,722 parameters on 5\,000 training images, deflated by five power-iteration
components: an estimate, not an exact trace, and a different object from the eigenvalues of
Table~\ref{tab:hessian-all}, which use 268\,336 weights and 1\,000-image probes.}
\label{tab:input-grid}
\centering\small
\begin{tabular}{@{}llrrrrrr@{}}
\toprule
Recipe & Method & $n$ & Test acc.\ (\%) & Train CE & Test CE & $\mathbb E\|J\|_F$ & $\widehat{\mathrm{tr}}(H)$\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}""")


# --------------------------------------------------------------------- figures

def fig_sensitivity(paired):
    for policies, name in ((["saved", "recalibrated"], "sensitivity_summary"),
                           (["centre_frozen"], "sensitivity_centre_frozen")):
        fig, axes = plt.subplots(len(policies), 2, figsize=(7.0, 2.7 * len(policies) + .3),
                                 squeeze=False, layout="constrained")
        for i, pol in enumerate(policies):
            for j, split in enumerate(("train_probe", "test_probe")):
                ax = axes[i, j]
                ax.axhline(0, color="#555555", lw=.8)
                for m in M[1:]:
                    g = paired[(paired.policy == pol) & (paired.split == split)
                               & (paired.method == m)].sort_values("amplitude")
                    x = g.amplitude.to_numpy()
                    y = g.mean_delta.to_numpy()
                    sd = g.sd_delta.to_numpy()
                    assert len(x) == 10
                    ax.plot(x, y, "o-", ms=3.2, lw=1.4, color=COLOR[m], label=LONG[m])
                    ax.fill_between(x, y - sd, y + sd, color=COLOR[m], alpha=.13, lw=0)
                ax.set_xscale("log")
                ax.set_xticks([.005, .01, .025, .05, .1, .25, .5],
                              [".005", ".01", ".025", ".05", ".1", ".25", ".5"])
                ax.tick_params(axis="x", labelsize=8)
                ax.set_xlabel(r"Relative amplitude $\varepsilon$ (log scale)")
                ax.set_ylabel(r"$\Delta S$ against plain (nats)")
                ax.grid(alpha=.18)
                ax.set_title("%s, %s probe" % (POLICY[pol], "train" if j == 0 else "test"))
        h = [plt.Line2D([], [], color=COLOR[m], marker="o", ms=3.2, lw=1.4, label=LONG[m])
             for m in M[1:]]
        h.append(plt.Line2D([], [], color="0.4", lw=6, alpha=.2,
                            label="$\\pm1$ sample SD over 5 seeds"))
        fig.legend(handles=h, loc="outside lower center", ncol=4, frameon=False)
        save(fig, name)


def fig_surfaces(planes):
    g0 = planes[(planes.seed == 0) & (planes.grid == 41)]
    fig = plt.figure(figsize=(7.2, 6.7), layout="constrained")
    vals = []
    for m in M:
        g = g0[g0.method == m]
        c = float(g[(g.a == 0) & (g.b == 0)].train_probe_ce.iloc[0])
        vals.extend((g.train_probe_ce - c).tolist())
    norm = Normalize(vmin=min(vals), vmax=max(vals))
    axes, surf = [], None
    for i, m in enumerate(M):
        ax = fig.add_subplot(2, 2, i + 1, projection="3d")
        axes.append(ax)
        g = g0[g0.method == m]
        c = float(g[(g.a == 0) & (g.b == 0)].train_probe_ce.iloc[0])
        z = (g.pivot(index="b", columns="a", values="train_probe_ce")
             .sort_index().sort_index(axis=1) - c)
        assert z.shape == (41, 41) and not z.isna().any().any()
        xx, yy = np.meshgrid(z.columns, z.index)
        surf = ax.plot_surface(xx, yy, z.to_numpy(), cmap="viridis", norm=norm, rstride=2,
                               cstride=2, linewidth=.2, edgecolor=(0, 0, 0, .12), antialiased=True)
        ax.set_title("%s, centre CE %.3f nats" % (LONG[m], c))
        ax.set_xlabel(r"direction 1 ($\varepsilon$)", labelpad=0)
        ax.set_ylabel(r"direction 2 ($\varepsilon$)", labelpad=0)
        ax.set_zlabel("")  # the vertical axis is named once, on the shared colour bar
        ax.set_xlim(-.5, .5)
        ax.set_ylim(-.5, .5)
        ax.set_zlim(min(vals), max(vals))
        ax.set_xticks([-.5, 0, .5])
        ax.set_yticks([-.5, 0, .5])
        ax.view_init(24, -55)
        ax.tick_params(labelsize=8, pad=0)
    fig.colorbar(surf, ax=axes, shrink=.6, location="right",
                 label="CE above the centre of that model (nats)", pad=.05)
    save(fig, "random_surfaces_wide")


PAIR_LABEL = {"plain_resolution": ("Plain", "R"), "plain_gaussian": ("Plain", "G"),
              "plain_combined": ("Plain", "RG"), "resolution_combined": ("R", "RG")}


def fig_interpolation(interp):
    fig, axes = plt.subplots(2, 4, figsize=(9, 4.9), layout="constrained")
    for j, pair in enumerate(["plain_resolution", "plain_gaussian", "plain_combined",
                              "resolution_combined"]):
        for k, split in enumerate(("train_probe", "test_probe")):
            ax = axes[k, j]
            for seed, z in interp[interp.pair == pair].groupby("seed"):
                z = z.sort_values("alpha")
                assert len(z) == 51
                ax.plot(z.alpha, z[split + "_ce"], lw=1.1, label="seed %d" % seed)
            a, b = PAIR_LABEL[pair]
            ax.set_title("%s $\\to$ %s" % (a, b))
            ax.set_xlabel(r"$\alpha$: weight interpolation")
            ax.set_ylabel("%s CE (nats)" % ("Train probe" if k == 0 else "Test probe"))
            ax.grid(alpha=.2)
    h = [plt.Line2D([], [], color="C%d" % s, lw=1.1, label="seed %d" % s) for s in range(5)]
    fig.legend(handles=h, loc="outside lower center", ncol=5, frameon=False)
    save(fig, "interpolation_summary")


def fig_input(freq, cells):
    ref = cells[cells.recipe_variant == "reference"]
    eps = [.05, .1, .25, .5, 1, 2, 3, 6, 12]
    fig, axes = plt.subplots(1, 2, figsize=(7, 2.2), layout="constrained")
    for m in M:
        g = (freq[(freq.method == m) & (freq.recipe_variant == "reference")]
             .groupby("radius").energy_fraction.agg(["mean", "std"]))
        axes[0].plot(g.index, g["mean"], color=COLOR[m], lw=1.4, label=LONG[m])
        axes[0].fill_between(g.index, g["mean"] - g["std"], g["mean"] + g["std"],
                             color=COLOR[m], alpha=.12, lw=0)
        z = ref[ref.method == m]
        axes[1].plot(eps, [z["logit_displacement_eps%g" % e].mean() for e in eps], "o-", ms=3.2,
                     lw=1.4, color=COLOR[m], label=LONG[m])
    axes[0].set_xlabel("Spatial frequency radius (cycles/image)")
    axes[0].set_ylabel("Fraction of Jacobian energy")
    axes[0].set_title("Input-Jacobian spectrum")
    h = [plt.Line2D([], [], color=COLOR[m], lw=1.4, label=LONG[m]) for m in M]
    h.append(plt.Line2D([], [], color="0.4", lw=6, alpha=.2, label="$\\pm1$ SD over 3 seeds"))
    fig.legend(handles=h, loc="outside lower center", ncol=5, frameon=False)
    axes[1].set_xscale("log")
    axes[1].set_xlabel(r"Input displacement $\varepsilon$ ($L^2$ norm, log scale)")
    axes[1].set_ylabel(r"Mean logit displacement $D(\varepsilon)$")
    axes[1].set_title("Finite input perturbation, not clipped to $[0,1]$")
    for ax in axes:
        ax.grid(alpha=.2)
    save(fig, "input_diagnostics")


# --------------------------------------------------------------------- prose macros

def macro(name, value):
    return "\\newcommand{\\%s}{%s}" % (name, value)


def numbers(S, large_paired, hess, endpoints, bars, pca, cells, trans, f64, hvp):
    L = ["% Numbers quoted in the prose, so text and tables cannot drift apart."]
    res = S[S.method == "resolution_max_b1"]
    L += [macro("tSettings", S.setting.nunique()),
          macro("tResPositiveSettings", int((res.gain_mean > 0).sum())),
          macro("tResPositivePairs", int(res.n_seeds_gain_positive.sum())),
          macro("tResPairs", int(res.n_seeds.sum())),
          macro("tResGainMin", "%.2f" % res.gain_mean.min()),
          macro("tResGainMax", "%.2f" % res.gain_mean.max())]
    for key, st in (("Stl", "stl10"), ("SubShort", "cifar10_5k/stl_budget"),
                    ("SubLong", "cifar10_5k/reference_updates")):
        g = S[(S.setting == st) & (S.method == "resolution_max_b1_gaussian_conv")].iloc[0]
        L += [macro("tRG%sGain" % key, "%.2f" % abs(g.gain_mean)),
              macro("tRG%sSeeds" % key, int(g.n_seeds_gain_positive))]
    g = S[S.setting == "sgd"].set_index("method")
    for m in M:
        L += [macro("tSgd%sAcc" % NAME[m], "%.2f" % g.loc[m].test_acc_mean),
              macro("tSgd%sAccSD" % NAME[m], "%.2f" % g.loc[m].test_acc_sd),
              macro("tSgd%sMinutes" % NAME[m], "%.1f" % g.loc[m].wall_minutes_mean)]
    gn = S[S.setting == "resnet20gn_cifar10"].set_index("method")
    stl = S[S.setting == "stl10"].set_index("method")
    for tag, src in (("Gn", gn), ("Stl", stl)):
        for m in ("plain", "resolution_max_b1"):
            L += [macro("t%s%sTrainCE" % (tag, NAME[m]), "%.3f" % src.loc[m].train_probe_ce_mean),
                  macro("t%s%sTestCE" % (tag, NAME[m]), "%.3f" % src.loc[m].test_ce_mean)]
    e = endpoints.groupby("method")
    for m in M:
        L += [macro("tLand%sTrainCE" % NAME[m], "%.3f" % e.get_group(m).train_full_ce.mean()),
              macro("tLand%sTestCE" % NAME[m], "%.3f" % e.get_group(m).test_full_ce.mean())]
    for m in M[1:]:
        for amp, atag in ((0.1, "One"), (0.25, "Quarter")):
            r = large_paired[(large_paired.method == m)
                             & (large_paired.policy == "recalibrated")
                             & (large_paired.evaluation_set == "test_full")
                             & (large_paired.amplitude == amp)].iloc[0]
            L += [macro("t%sPointTestFull%sDelta" % (NAME[m], atag), "%+.3f" % r.mean_delta),
                  macro("t%sPointTestFull%sBelow" % (NAME[m], atag), int(r.n_seeds_below_plain)),
                  macro("t%sPointTestFull%sAbove" % (NAME[m], atag),
                        int(r.n_seeds - r.n_seeds_below_plain))]
    ratios = []
    for _, g in hess.groupby(["policy", "coords", "probe"]):
        w = g.pivot(index="seed", columns="method", values="top1")
        for m in M[1:]:
            ratios.extend((w[m] / w["plain"]).tolist())
    L += [macro("tHessProblems", len(hess)),
          macro("tHessRatioMin", "%.2f" % min(ratios)),
          macro("tHessRatioMax", "%.2f" % max(ratios)),
          macro("tHessGradMin", "%.2f" % hess.grad_norm.min()),
          macro("tHessGradMax", "%.2f" % hess.grad_norm.max()),
          macro("tHessIterMin", int(min(hess.iterations_start0.min(),
                                        hess.iterations_start1.min()))),
          macro("tHessIterMax", int(max(hess.iterations_start0.max(),
                                        hess.iterations_start1.max()))),
          macro("tHessResidTop", "%.1f" % (1e7 * max(hess.top1_rel_resid.max(),
                                                     hess.top2_rel_resid.max()))),
          macro("tHessResidMin", "%.2f" % (1e4 * hess.min_rel_resid.max()))]
    wt = bars.pivot(index="seed", columns="pair", values="train_probe_barrier")
    we = bars.pivot(index="seed", columns="pair", values="test_probe_barrier")
    low_t = sorted(int(s) for s in wt.index[wt["resolution_combined"] < wt["plain_resolution"]])
    low_e = sorted(int(s) for s in we.index[we["resolution_combined"] < we["plain_resolution"]])
    listing = lambda xs: (", ".join(str(x) for x in xs[:-1]) + " and " + str(xs[-1])  # noqa: E731
                          if len(xs) > 1 else str(xs[0]))
    L += [macro("tBarrierTrainSeeds", listing(low_t)), macro("tBarrierTrainCount", len(low_t)),
          macro("tBarrierTestSeeds", listing(low_e)), macro("tBarrierTestCount", len(low_e)),
          macro("tPcaTwoLow", "%.1f" % (100 * pca.evr_pc1_2.min())),
          macro("tPcaTwoHigh", "%.1f" % (100 * pca.evr_pc1_2.max())),
          macro("tPcaFourLow", "%.1f" % (100 * pca.evr_pc1_4.min())),
          macro("tPcaFourHigh", "%.1f" % (100 * pca.evr_pc1_4.max()))]
    ref = cells[cells.recipe_variant == "reference"].groupby("method")
    for m in M:
        L += [macro("tJac%sRadius" % NAME[m], "%.2f" % ref.get_group(m).freq_mean_radius.mean()),
              macro("tJac%sTrace" % NAME[m], thousands(ref.get_group(m).trace_deflated.mean()))]
    L += [macro("tGridConverged", int(cells.top5_converged.sum())),
          macro("tGridEstimates", 5 * len(cells)),
          macro("tGridCells", len(cells))]
    t = trans[(trans.method == "gaussian_postrelu") & (trans.epoch == 3)
              & (trans.policy == "recalibrated")].set_index("split")
    L += [macro("tGaussEpochThreeTrain", int(t.loc["train_probe"].n_seeds_next_state_lower)),
          macro("tGaussEpochThreeTest", int(t.loc["test_probe"].n_seeds_next_state_lower)),
          macro("tFloatChecks", thousands(len(f64))),
          macro("tFloatMaxDiff", "%.1f" % (1e7 * f64.abs_diff.max())),
          macro("tHvpSymmetry", "%.1f" % (1e6 * hvp.symmetry_rel.max())),
          macro("tHvpPrecision", "%.1f" % (1e4 * hvp.hvp_f32_vs_f64_rel.max()))]
    tex("numbers_generated", "\n".join(L))


# --------------------------------------------------------------------- catalogue table

def catalogue_table(cfg):
    from build_catalogue import ORDER, num, tex as ltex
    rows = []
    for eid in ORDER:
        g = cfg[cfg.experiment == eid]
        if g.empty:
            continue
        head = g.iloc[0]
        rows.append(r"\multicolumn{5}{@{}p{\linewidth}@{}}{\rule{0pt}{2.8ex}\textbf{%s}}\\*"
                    % ltex(head.experiment_title))
        rows.append(r"\multicolumn{5}{@{}p{\linewidth}@{}}{\footnotesize %s}\\*" % ltex(
            "%s. Evaluation split: %s. Timing: %s." % (str(head.conditions).rstrip("."),
                                                       head.evaluation_split or "n/a",
                                                       head.timing_scope)))
        for r in g.itertuples():
            label = r.label + (" (diverged)" if r.status != "valid" else "")
            if isinstance(r.flags, str) and r.flags:
                label += " (%s)" % r.flags.replace(";", ", ")
            rows.append("%s & %s & %s & %d/%d & %s\\\\" % (
                ltex(label), num(r.acc_mean), num(r.acc_sd), r.seeds_valid, r.seeds_attempted,
                "---" if pd.isna(r.wall_seconds_mean) else "%.0f" % r.wall_seconds_mean))
    tex("catalogue_compact", r"""\begingroup\small
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{4.05in}rrcr@{}}
\caption{Historical configuration catalogue, recomputed from the per-run records. Accuracy is the
final recorded evaluation of each run, averaged over its numerically valid seeds, in percent; SD is
the sample SD over those seeds in percentage points, absent with a single valid seed. Seeds are
valid/attempted, so diverged runs stay visible. Wall time is the mean over valid runs on the timing
scope of the group heading. Groups differ in data, budget and evaluation split, so rows are
comparable only within a group.}\label{tab:catalogue}\\
\toprule Configuration & Acc.\ (\%) & SD & Seeds & Wall (s)\\\midrule\endfirsthead
\toprule Configuration & Acc.\ (\%) & SD & Seeds & Wall (s)\\\midrule\endhead
\midrule\multicolumn{5}{r}{Continued on next page}\\\endfoot
\bottomrule\endlastfoot
""" + "\n".join(rows) + "\n" + r"\end{longtable}\endgroup")


# --------------------------------------------------------------------- main

def main():
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    # Final manuscript layout; shares the audited records and numeric conventions.
    from paper_layout import (benchmark_tables, landscape_tables, input_tables,
                              fig_sensitivity, fig_surfaces, selection_table)
    S = rec("benchmark_settings")
    paired = rec("landscape_sensitivity_paired")
    per_seed = rec("landscape_sensitivity_per_seed")
    large = rec("landscape_large_set_per_seed")
    large_paired = rec("landscape_large_set_paired")
    hess = rec("landscape_hessian")
    endpoints = rec("landscape_endpoints")
    bars = rec("landscape_interpolation_barriers")
    interp = rec("landscape_interpolation")
    pca = rec("landscape_pca")
    planes = rec("landscape_random_planes")
    cells = rec("input_diagnostics_cells")
    freq = rec("input_diagnostics_frequency")
    trans = rec("landscape_transitions_audit")
    f64 = rec("landscape_float64_checks")
    hvp = rec("landscape_hvp_checks")
    cfg = rec("catalogue_configurations")
    cat_cells = rec("catalogue_cells")

    benchmark_tables(S)
    selection_table(S, rec("benchmark_runs"))
    landscape_tables(large, large_paired, hess, endpoints)
    input_tables(cells)
    catalogue_table(cfg)
    fig_sensitivity(paired)
    fig_surfaces(planes)
    fig_interpolation(interp)
    fig_input(freq, cells)
    numbers(S, large_paired, hess, endpoints, bars, pca, cells, trans, f64, hvp)

    res = S[S.method == "resolution_max_b1"]
    top1 = {k: g.pivot(index="seed", columns="method", values="top1")
            for k, g in hess.groupby(["policy", "coords", "probe"])}
    checks = {
        "benchmark_settings": int(S.setting.nunique()),
        "benchmark_runs_behind_them": int(S.n_seeds.sum()),
        "resolution_settings_with_positive_mean_gain": int((res.gain_mean > 0).sum()),
        "resolution_positive_seed_pairs": int(res.n_seeds_gain_positive.sum()),
        "sensitivity_seed_rows": len(per_seed),
        "sensitivity_paired_rows": len(paired),
        "directions_per_checkpoint": sorted(set(per_seed.n_directions.tolist())),
        "large_set_rows": len(large),
        "hessian_problems": len(hess),
        "hessian_all_converged_both_starts": bool(hess.converged_start0.all()
                                                  and hess.converged_start1.all()),
        "hessian_top1_below_plain_in_every_seed": bool(
            all((w[M[1:]].lt(w["plain"], axis=0)).all().all() for w in top1.values())),
        "hessian_min_all_negative": bool((hess["min"] < 0).all()),
        "hessian_max_rel_resid": {k: float(hess[k].max()) for k in
                                  ("top1_rel_resid", "top2_rel_resid", "min_rel_resid")},
        "gradient_norm_range": [float(hess.grad_norm.min()), float(hess.grad_norm.max())],
        "float64_comparisons": len(f64),
        "float64_max_abs_difference": float(f64.abs_diff.max()),
        "hvp_repeat_bitwise": bool(hvp.hvp_repeat_bitwise.all()),
        "hvp_max_symmetry_rel": float(hvp.symmetry_rel.max()),
        "hvp_max_f32_f64_rel": float(hvp.hvp_f32_vs_f64_rel.max()),
        "plane_vertices_missing": int(planes.train_probe_ce.isna().sum()),
        "interpolation_points_per_segment": sorted(set(bars.n_points.tolist())),
        "interpolation_all_barriers_positive": bool(
            (bars.train_probe_barrier > 0).all() and (bars.test_probe_barrier > 0).all()),
        "input_grid_cells": len(cells),
        "input_grid_top5_converged": int(cells.top5_converged.sum()),
        "catalogue_configurations": len(cfg),
        "catalogue_runs": len(cat_cells),
        "catalogue_configurations_with_an_accuracy": int(cfg.acc_mean.notna().sum()),
        "catalogue_configurations_without_a_valid_seed": int(cfg.acc_mean.isna().sum()),
        "catalogue_values_matching_the_supplied_index": int(
            ((cfg.acc_mean - cfg.index_acc_mean).abs() < 5e-3).sum()),
    }
    (PAPER / "evidence" / "RECOMPUTED_CHECKS.json").write_text(
        json.dumps(checks, indent=1) + "\n", encoding="utf-8")
    print(json.dumps(checks, indent=1))


if __name__ == "__main__":
    main()
