"""Generate and push one Kaggle kernel per STL-10 method.

One kernel per method rather than one for all four: each then fits comfortably
inside the session limit, they queue independently, and a failure costs one run
rather than the campaign.

The kernel clones this repository at a pinned commit instead of carrying the
code as a dataset, so ``Trainer.provenance()`` records a real git SHA in every
``summary.json``.  That needs ``enable_internet``; if internet has to stay off,
push the tree as a dataset, attach it, and drop the clone step -- at the cost of
``code_version()`` returning ``None``.

Usage::

    py scripts/kaggle/push_stl10.py --dry-run        # write the kernels, push nothing
    py scripts/kaggle/push_stl10.py --seeds 0        # write and push

Then, once a kernel reports ``complete``::

    kaggle kernels status  aubincharley/stl10-<method>-seed0
    kaggle kernels output  aubincharley/stl10-<method>-seed0 -p runs/stl10
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

import stl10_configs as S                                              # noqa: E402

REPO = "https://github.com/aubincharley/homotogit.git"
BRANCH = "continuation-core"
#: STL-10 labelled binaries, 360 MB.  pratt3000/stl10-binary-files has the
#: stl10_binary/ folder name already but drags in a 2.7 GB unlabeled_X.bin that
#: continuation_core.data never reads.
DATASET = "yellowflag/stl10labeled2"

KERNEL = '''"""STL-10 continuation run: {method}, seed {seed}.

Generated by scripts/kaggle/push_stl10.py -- edit that, not this.
Commit {commit}.
"""
import glob
import os
import subprocess
import sys

REPO_DIR = "/tmp/homotogit"
OUT = "/kaggle/working/runs"
METHOD = "{method}"
SEED = {seed}
COMMIT = "{commit}"


def run(*cmd, **kw):
    print("$", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, **kw)


# -- hardware, first, so the log says what this ran on ------------------------
import torch
if not torch.cuda.is_available():
    raise SystemExit("no GPU: the accelerator request did not take effect, and "
                     "96x96 on CPU is not worth the session")
print("torch", torch.__version__, "|", torch.cuda.get_device_name(0),
      "| capability sm_%d%d" % torch.cuda.get_device_capability(0), flush=True)
# is_available() is not enough: a Tesla P100 (sm_60) reports True under a torch
# built for sm_70+, then fails on the first real kernel launch.  Launch one now.
try:
    torch.linalg.norm(torch.ones(64, 64, device="cuda") @ torch.ones(64, 64, device="cuda"))
    torch.cuda.synchronize()
except RuntimeError as exc:
    raise SystemExit("GPU present but unusable by this torch build (%s): %s"
                     % (torch.cuda.get_device_name(0), exc))


# -- code: a pinned commit, so summary.json provenance records a real SHA -----
run("git", "clone", "--branch", "{branch}", "--single-branch", "{repo}", REPO_DIR)
run("git", "-C", REPO_DIR, "checkout", "--detach", COMMIT)
os.chdir(REPO_DIR)
sys.path.insert(0, REPO_DIR)

# -- data --------------------------------------------------------------------
# continuation_core.data wants <root>/stl10_binary/train_X.bin.  Kaggle mounts a
# dataset under a slug we should not have to guess (and guessed wrong once), and
# this dataset keeps the binaries at its root rather than in a stl10_binary/
# folder.  So find train_X.bin and link whatever directory holds it.
print("/kaggle/input:", sorted(os.listdir("/kaggle/input")), flush=True)
found = sorted(glob.glob("/kaggle/input/**/train_X.bin", recursive=True))
if not found:
    raise SystemExit("no train_X.bin under /kaggle/input; tree: %s"
                     % sorted(glob.glob("/kaggle/input/**/*", recursive=True))[:40])
src = os.path.dirname(found[0])
os.makedirs("data", exist_ok=True)
if os.path.islink("data/stl10_binary"):
    os.unlink("data/stl10_binary")
os.symlink(src, "data/stl10_binary")
print("data/stl10_binary ->", src, sorted(os.listdir("data/stl10_binary")), flush=True)

PY = [sys.executable, "-m", "continuation_core"]

# -- assets: new index arrays, initial weights copied from the CIFAR-10 set ---
# Generated for 90 epochs though we run 60: Trainer only needs perms.shape[0] >=
# epochs, and regenerating later would change the .npz digest and void pairing
# with these runs.  With --init-from no torch RNG is touched, so this is
# bit-identical to the set any other machine would produce.
run(*PY, "make-assets", "--dataset", "stl10", "--data-root", "data",
    "--arch", "resnet20_bn_cifar", "--epochs", "90", "--seeds", "0,1,2",
    "--init-from", "assets/cifar10_resnet20bn", "--out", "assets/stl10_resnet20bn")

# -- configs: every transfer decision lives in scripts/stl10_configs.py -------
run(sys.executable, "scripts/stl10_configs.py", "--data-root", "data",
    "--assets", "assets/stl10_resnet20bn", "--seeds", str(SEED),
    "--out", "configs/stl10", "--run-out", OUT)

CONFIG = "configs/stl10/%s__seed%d.json" % (METHOD, SEED)
print(open(CONFIG).read(), flush=True)

# -- dry run: aborts the kernel unless the target state is bitwise plain ------
run(*PY, "dry-run", "--config", CONFIG, "--report", OUT + "/dryrun_%s.json" % METHOD)

# -- train -------------------------------------------------------------------
run(*PY, "train", "--config", CONFIG, "--out", OUT)
run("cp", "-r", "configs/stl10", OUT + "/configs")
run("cp", "assets/stl10_resnet20bn/assets_manifest.json",
    OUT + "/stl10_assets_manifest.json")
print("done", flush=True)
'''

METADATA = {
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": True,
    # enable_gpu alone gave a Tesla P100 (sm_60), which Kaggle's torch
    # 2.10.0+cu128 does not support (it needs sm_70+): cuda.is_available() is
    # True but every kernel launch fails.  The reference CIFAR-10 runs were on
    # T4s, so ask for the same card by name.
    "machine_shape": "NvidiaTeslaT4",
    "enable_tpu": False,
    "enable_internet": True,
    "keywords": [],
    "dataset_sources": [DATASET],
    "kernel_sources": [],
    "competition_sources": [],
    "model_sources": [],
}


def head_commit() -> str:
    return subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                          capture_output=True, text=True, check=True).stdout.strip()


def commit_is_on_origin(commit: str) -> bool:
    r = subprocess.run(["git", "-C", str(ROOT), "branch", "-r", "--contains", commit],
                       capture_output=True, text=True)
    return r.returncode == 0 and "origin/" in r.stdout


def write(method: str, seed: int, commit: str, user: str, out_root: Path) -> Path:
    slug = "stl10-%s-seed%d" % (method.replace("_", "-"), seed)
    d = out_root / slug
    d.mkdir(parents=True, exist_ok=True)
    (d / (slug + ".py")).write_text(KERNEL.format(
        method=method, seed=seed, commit=commit, repo=REPO, branch=BRANCH))
    meta = dict(METADATA, id="%s/%s" % (user, slug),
                # the title must slugify to the id, or Kaggle warns and the
                # two can drift apart
                title=slug.replace("-", " "),
                code_file=slug + ".py")
    (d / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
    return d


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seeds", default="0")
    ap.add_argument("--methods", default=",".join(S.METHODS))
    ap.add_argument("--user", default="aubincharley")
    ap.add_argument("--commit", help="default: HEAD, which must be pushed to origin")
    ap.add_argument("--out", default=str(Path(__file__).parent / "kernels"))
    ap.add_argument("--dry-run", action="store_true", help="write the kernels, push nothing")
    args = ap.parse_args(argv)

    commit = args.commit or head_commit()
    if not commit_is_on_origin(commit):
        print("warning: %s is not on any origin branch; the kernel's git clone will "
              "fail until you push it" % commit[:12], file=sys.stderr)

    for seed in (int(s) for s in args.seeds.split(",")):
        for method in args.methods.split(","):
            d = write(method, seed, commit, args.user, Path(args.out))
            print("wrote", d)
            if args.dry_run:
                continue
            subprocess.run(["kaggle", "kernels", "push", "-p", str(d)], check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
