"""Publish inputs, push kernels, poll, pull and verify for the follow-up.

    py -m overnight.kaggle publish --accounts ... [--old-endpoints maxmonstre]
    py -m overnight.kaggle push --tag pilot --mode pilot --accounts maxlebossdu91
    py -m overnight.kaggle push --tag t1 --mode train --accounts ...      (queues from protocol/ALLOCATION.json)
    py -m overnight.kaggle push --tag eval --mode evaluate_old --accounts maxmonstre
    py -m overnight.kaggle status --tag t1 --accounts ...
    py -m overnight.kaggle pull --tag t1 --accounts ...
    py -m overnight.kaggle verify --tag t1 --accounts ...

Dataset ``<user>/overnight-inputs``: ``assets/`` (the pinned CIFAR-10 ResNet-20 set, unchanged),
``overnight_inputs_manifest.json`` (sha256 of every file) and, for the evaluation account only,
``old/<run>/`` with the 42 final checkpoints of the 30-epoch comparison, their configs and their
``panels.json``, plus ``old_endpoints_manifest.json``.  Code travels base64-zipped inside the
kernel script, with ``overnight/frozen_hashes.json``.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from . import matrix as MX

STAGE = MX.STUDY / "kaggle_stage"
RAW = MX.STUDY / "raw"
SLUG = "overnight-inputs"
ACCOUNTS = ("maxmonstre", "maxfrrsava", "maximemonstrenikez", "maxlebossdu91", "maxlefrr", "maxnicaise", "maxnikezz")
PREV = MX.PREV_STUDY_WORKTREE

WRAPPER = '''# generated by overnight/kaggle.py
import base64, io, os, subprocess, sys, zipfile, glob
repo = "/kaggle/working/_repo"
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
extra = {extra}
prev = sorted(glob.glob("/kaggle/input/**/ovn/COMPLETE.json", recursive=True))
if prev:
    extra += ["--resume", os.path.dirname(prev[0])]
args = [sys.executable, "-m", "overnight.job", "{mode}", "--out", "/kaggle/working/ovn"] + extra
r = subprocess.run(args, cwd=repo)
sys.exit(r.returncode)
'''


def env_for(acc):
    cfg = Path.home() / ".kaggle-accounts" / acc
    user = json.loads((cfg / "kaggle.json").read_text())["username"]
    return {**os.environ, "KAGGLE_CONFIG_DIR": str(cfg)}, user


def run(cmd, env):
    exe = shutil.which("kaggle") or "kaggle"
    r = subprocess.run([exe] + cmd[1:], text=True, capture_output=True, env=env, encoding="utf-8", errors="replace")
    print("$ " + " ".join(cmd) + "\n" + ((r.stdout or "") + (r.stderr or ""))[-1500:], flush=True)
    return r


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def old_endpoint_sources() -> dict:
    """run -> (checkpoint path, config path or None, panels.json path) for the 42 previous cells."""
    out = {}
    for p in sorted((PREV / "raw" / "main").glob("*/cmp/cells/*/panels.json")):
        cell = p.parent
        run_name = cell.name
        ck = cell / "checkpoints" / "epoch_030.pt"
        if ck.exists():
            out[run_name] = (ck, None, p)
        else:                                            # reused landscape_v2 endpoints (SGD historical arms)
            src = next(PREV.glob("kaggle_stage/inputs_*/reused/%s" % run_name))
            out[run_name] = (src / "epoch_030.pt", src / "config.json", p)
    return out


def publish(accounts, old_account):
    for acc in accounts:
        d = STAGE / ("inputs_" + acc)
        if d.exists():
            shutil.rmtree(d)
        (d / "assets").mkdir(parents=True)
        for f in (MX.ROOT / "assets" / "cifar10_resnet20bn").iterdir():
            shutil.copy2(f, d / "assets" / f.name)
        if acc == old_account:
            srcs = old_endpoint_sources()
            if len(srcs) != 42:
                raise SystemExit("expected 42 previous endpoints, found %d" % len(srcs))
            man = {"endpoints": {}}
            for run_name, (ck, cfg, panels) in srcs.items():
                dst = d / "old" / run_name
                dst.mkdir(parents=True)
                shutil.copy2(ck, dst / "epoch_030.pt")
                shutil.copy2(panels, dst / "panels.json")
                if cfg is not None:
                    shutil.copy2(cfg, dst / "config.json")
                pj = json.loads(Path(panels).read_text())
                got = sha(dst / "epoch_030.pt")
                if got != pj["checkpoint_sha256"]:
                    raise SystemExit("checkpoint %s does not match its panels.json digest" % run_name)
                man["endpoints"][run_name] = {"checkpoint_file": "epoch_030.pt", "checkpoint_sha256": got,
                                              "source": str(Path(ck).relative_to(PREV.parents[1])).replace("\\", "/")}
            (d / "old_endpoints_manifest.json").write_text(json.dumps(man, indent=1))
        files = {p.relative_to(d).as_posix(): {"sha256": sha(p), "bytes": p.stat().st_size}
                 for p in sorted(d.rglob("*")) if p.is_file()}
        (d / "overnight_inputs_manifest.json").write_text(json.dumps({"files": files}, indent=1))
        env, user = env_for(acc)
        (d / "dataset-metadata.json").write_text(json.dumps({"title": "overnight inputs", "id": "%s/%s" % (user, SLUG),
                                                             "licenses": [{"name": "unknown"}]}))
        r = run(["kaggle", "datasets", "create", "-p", str(d), "--dir-mode", "zip"], env)
        txt = (r.stdout or "") + (r.stderr or "")
        if r.returncode or "already" in txt.lower() or "error" in txt.lower():
            r = run(["kaggle", "datasets", "version", "-p", str(d), "-m", "inputs", "--dir-mode", "zip"], env)
            if r.returncode:
                raise SystemExit("publish failed for %s" % acc)


def payload():
    buf, files = io.BytesIO(), []
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "comparison", "overnight", "tests"):
            for p in sorted((MX.ROOT / pkg).rglob("*")):
                if p.suffix in (".py", ".json") and "__pycache__" not in p.parts:
                    rel = p.relative_to(MX.ROOT).as_posix()
                    zf.write(p, rel)
                    files.append({"path": rel, "sha256": sha(p)})
    return base64.b64encode(buf.getvalue()).decode("ascii"), files


def kid(acc, tag):
    return "%s/ovn-%s-%s" % (env_for(acc)[1], tag, acc.lower())


def push(accounts, tag, mode, hours, resume_from):
    b64, files = payload()
    alloc = json.loads((MX.STUDY / "protocol" / "ALLOCATION.json").read_text()) if mode == "train" else {}
    for acc in accounts:
        env, user = env_for(acc)
        d = STAGE / ("kernel_%s_%s" % (tag, acc))
        d.mkdir(parents=True, exist_ok=True)
        extra = ["--hours", str(hours)]
        if mode == "train":
            extra += ["--queues", json.dumps(alloc["accounts"][acc]["queues"])]
        (d / "script.py").write_text(WRAPPER.format(payload=b64, mode=mode, extra=json.dumps(extra)), encoding="utf-8")
        sources = ["%s/ovn-%s-%s" % (user, resume_from, acc.lower())] if resume_from else []
        (d / "kernel-metadata.json").write_text(json.dumps({
            "id": kid(acc, tag), "title": "ovn-%s-%s" % (tag, acc.lower()), "code_file": "script.py",
            "language": "python", "kernel_type": "script", "is_private": True, "enable_gpu": True,
            "enable_internet": False, "enable_tpu": False, "machine_shape": "NvidiaTeslaT4",
            "dataset_sources": ["pankrzysiu/cifar10-python", "%s/%s" % (user, SLUG)],
            "kernel_sources": sources, "competition_sources": []}, indent=2))
        RAW.mkdir(parents=True, exist_ok=True)
        (RAW / ("launch_%s_%s.json" % (tag, acc))).write_text(json.dumps({
            "account": acc, "kernel": kid(acc, tag), "mode": mode, "tag": tag, "hours": hours,
            "queues": alloc.get("accounts", {}).get(acc, {}).get("queues"), "resume_from_kernel": sources,
            "launched_utc": datetime.now(timezone.utc).isoformat(), "script_sha256": sha(d / "script.py"),
            "payload_files": files}, indent=1))
        if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
            print("PUSH FAILED for %s" % acc)


def pull(acc, tag, pattern=None, attempts=4):
    """Kernel output through the Python API in a subprocess (the CLI aborted with a JSON error on
    large outputs); retried, then checked by ``verify``."""
    import sys
    import time
    dest = RAW / tag / acc
    dest.mkdir(parents=True, exist_ok=True)
    env, _ = env_for(acc)
    code = ("from kaggle.api.kaggle_api_extended import KaggleApi; api = KaggleApi(); api.authenticate(); "
            "api.kernels_output(%r, path=%r, force=True, quiet=True, file_pattern=%r); print('pulled')"
            % (kid(acc, tag), str(dest), pattern or "ovn/(?!_repo)"))
    for i in range(attempts):
        r = subprocess.run([sys.executable, "-c", code], env=env, capture_output=True, text=True, encoding="utf-8", errors="replace")
        print(acc, tag, "attempt", i + 1, (r.stdout + r.stderr)[-400:].strip())
        if r.returncode == 0:
            return True
        time.sleep(10)
    return False


def verify(acc, tag):
    root = RAW / tag / acc / "ovn"
    rep = {"account": acc, "tag": tag}
    m = root / "MANIFEST.json"
    if not m.exists():
        rep["manifest"] = "MISSING"
    else:
        listed = json.loads(m.read_text())
        missing = [r for r in listed if not (root / r).exists()]
        bad = [r for r in listed if (root / r).exists() and sha(root / r) != listed[r]["sha256"]]
        rep["manifest"] = {"listed": len(listed), "missing": missing, "hash_mismatch": bad}
    for f in ("environment.json", "COMPLETE.json", "inputs_check.json"):
        rep[f] = json.loads((root / f).read_text()) if (root / f).exists() else "MISSING"
    (RAW / ("verify_%s_%s.json" % (tag, acc))).write_text(json.dumps(rep, indent=1))
    c = rep["COMPLETE.json"]
    print(acc, tag, "manifest", rep["manifest"] if isinstance(rep["manifest"], str) else
          {k: (v if isinstance(v, int) else len(v)) for k, v in rep["manifest"].items()},
          "complete", None if c == "MISSING" else {"all_done": c.get("all_done"), "n": len(c.get("cells", {}))})
    return rep


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=("publish", "push", "status", "pull", "verify"))
    ap.add_argument("--tag", default="t1")
    ap.add_argument("--mode", default="train", choices=("pilot", "train", "evaluate_old"))
    ap.add_argument("--accounts", nargs="*", default=list(ACCOUNTS))
    ap.add_argument("--old-endpoints", default="maxmonstre")
    ap.add_argument("--hours", type=float, default=11.0)
    ap.add_argument("--resume-from")
    ap.add_argument("--pattern")
    a = ap.parse_args()
    if a.action == "publish":
        publish(a.accounts, a.old_endpoints)
    elif a.action == "push":
        push(a.accounts, a.tag, a.mode, a.hours, a.resume_from)
    elif a.action == "status":
        for acc in a.accounts:
            run(["kaggle", "kernels", "status", kid(acc, a.tag)], env_for(acc)[0])
    elif a.action == "pull":
        for acc in a.accounts:
            pull(acc, a.tag, a.pattern)
    else:
        for acc in a.accounts:
            verify(acc, a.tag)


if __name__ == "__main__":
    main()
