"""Emit the LaTeX data files behind the two schema figures.

    figures/gaussian_sites/data.tex   -- insertion sites, stage widths, sigma rule
    figures/resolution/data.tex       -- the four resolution schedules, the
                                         sigma schedule, the adaptive windows

Every value is imported from the modules that the campaign actually runs
(``continuation.campaign_ops`` and ``scripts.campaign_manifest``), so the
figures cannot drift from the code.  Nothing here is transcribed by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from continuation.campaign_ops import (EARLY7, N_SITES, SITE_WIDTH_AT_32,  # noqa: E402
                                       STAGE_OF_SITE, adaptive_windows)
from scripts.campaign_manifest import (BYPASS_FROM, EPOCHS,  # noqa: E402
                                       GAUSSIAN, RESOLUTIONS)

SITES = ROOT / "figures" / "gaussian_sites" / "data.tex"
RES = ROOT / "figures" / "resolution" / "data.tex"
HEADER = ("%% generated by scripts/fig_schema_data.py from the campaign modules\n"
          "%% -- do not edit; re-run the script instead\n")


def staircase(values):
    """Compress a per-epoch series into TikZ coordinates at its change points."""
    pts, start = [], 0
    for e in range(1, len(values) + 1):
        if e == len(values) or values[e] != values[start]:
            pts.append((start, values[start]))
            pts.append((e, values[start]))
            start = e
    return " ".join("(%g,%g)" % (x, y) for x, y in pts)


def segments(values, fmt="%g"):
    """Compress a per-epoch series into ``start/end/value`` runs."""
    runs, start = [], 0
    for e in range(1, len(values) + 1):
        if e == len(values) or values[e] != values[start]:
            runs.append((start, e, values[start]))
            start = e
    return ", ".join(("%g/%g/" + fmt) % r for r in runs)


def levels(values):
    """The distinct held values of a schedule, in order of first appearance."""
    out = []
    for v in values:
        if not out or out[-1] != v:
            out.append(v)
    return out


def main():
    # ---- figure 2: where the blur is inserted -----------------------------
    stage_counts = [STAGE_OF_SITE.count(s) for s in sorted(set(STAGE_OF_SITE))]
    stage_widths = [SITE_WIDTH_AT_32[STAGE_OF_SITE.index(s)]
                    for s in sorted(set(STAGE_OF_SITE))]
    SITES.write_text(
        HEADER
        + "\\newcommand{\\nSites}{%d}\n" % N_SITES
        + "\\newcommand{\\nEarly}{%d}\n" % len(EARLY7)
        + "\\newcommand{\\earlyLast}{%d}\n" % EARLY7[-1]
        + "\\newcommand{\\groupCounts}{%s}\n"
          % ", ".join(str(c) for c in stage_counts)
        + "\\newcommand{\\groupWidths}{%s}\n"
          % ", ".join(str(w) for w in stage_widths)
        + "".join("\\newcommand{\\groupW%s}{%d}\n" % (n, w) for n, w in
                  zip(("one", "two", "three"), stage_widths))
        + "".join("\\newcommand{\\groupN%s}{%d}\n" % (n, c) for n, c in
                  zip(("one", "two", "three"), stage_counts))
        + "\\newcommand{\\bypassEpoch}{%d}\n" % BYPASS_FROM
        + "\\newcommand{\\nEpochs}{%d}\n" % EPOCHS)

    # ---- figure 3: the resolution schedules -------------------------------
    sig = GAUSSIAN["Gplateau"]
    body = [HEADER]
    for name, key in (("RTwo", "R32"), ("RProg", "Rprog"),
                      ("RGentle", "Rgentle"), ("RReverse", "Rreverse")):
        body.append("\\newcommand{\\path%s}{%s}\n"
                    % (name, staircase(RESOLUTIONS[key])))
        body.append("\\newcommand{\\segs%s}{%s}\n"
                    % (name, segments(RESOLUTIONS[key])))
    body.append("\\newcommand{\\pathSigma}{%s}\n" % staircase(sig))
    body.append("\\newcommand{\\segsSigma}{%s}\n" % segments(sig, "%.2f"))
    body.append("\\newcommand{\\sigmaLevels}{%s}\n"
                % ", ".join("%g" % v for v in levels(sig) if v > 0))
    body.append("\\newcommand{\\nEpochs}{%d}\n" % EPOCHS)
    body.append("\\newcommand{\\bypassEpoch}{%d}\n" % BYPASS_FROM)
    # the two honest facts about adaptive max pooling at these sizes
    for tag, r in (("Sixteen", 16), ("TwentyFour", 24)):
        w = adaptive_windows(32, r)
        widths = sorted({b - a for a, b in w})
        overlaps = sum(1 for j in range(1, len(w)) if w[j][0] < w[j - 1][1])
        body.append("\\newcommand{\\win%sWidths}{%s}\n"
                    % (tag, "/".join(str(x) for x in widths)))
        body.append("\\newcommand{\\win%sOverlaps}{%d}\n" % (tag, overlaps))
        body.append("\\newcommand{\\win%sList}{%s}\n"
                    % (tag, ", ".join("%d/%d" % (a, b) for a, b in w[:8])))
    RES.write_text("".join(body))

    print("sites   ->", SITES)
    print("res     ->", RES)
    for p in (SITES, RES):
        print("--", p.name)
        print(p.read_text().rstrip())


if __name__ == "__main__":
    main()
