"""Generate the ResNet-20-GN architecture schema with PlotNeuralNet pics.

Writes ``figures/gaussian_sites_pnn/body.tex``: the isometric layer stack, with
the Gaussian drawn as its own thin slab immediately after every hooked
convolution -- which is exactly where ``continuation.campaign_ops.attach_sites``
puts it (a forward hook on each main-path 3x3 conv, so the blur rewrites the
conv output before GroupNorm and before the ReLU).

Geometry and counts are imported from the campaign modules, never transcribed:
the stage layout comes from ``STAGE_OF_SITE`` / ``SITE_WIDTH_AT_32`` and the
early mask from ``EARLY7``.

The ``Box`` / ``Ball`` pics come from PlotNeuralNet
(https://github.com/HarisIqbal88/PlotNeuralNet, MIT), vendored under
``figures/gaussian_sites_pnn/layers/``.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from continuation.campaign_ops import (EARLY7, N_SITES,  # noqa: E402
                                       SITE_WIDTH_AT_32, STAGE_OF_SITE,
                                       SiteController)
from scripts.campaign_manifest import (BYPASS_FROM, EPOCHS,  # noqa: E402
                                       GAUSSIAN)

DIR = ROOT / "figures" / "gaussian_sites_pnn"
OUT = DIR / "body.tex"
PRE = DIR / "preamble.tex"
CAP = DIR / "caption.tex"

CHANNELS = (16, 32, 64)          # ResNetCifarGN widths, stage 1..3
BLOCKS_PER_STAGE = 3             # num_blocks = 3  ->  depth 6n + 2 = 20

# drawn size per stage: box height/depth track the feature-map side, box width
# tracks the channel count.  Purely visual scalings, chosen to fit a page.
BOX_H = {32: 15.0, 16: 9.5, 8: 6.0}      # drawn height per feature-map side
BOX_W = {16: 0.75, 32: 1.05, 64: 1.5}    # conv thickness per channel count
BLOCK_W = {16: 1.5, 32: 2.0, 64: 2.6}    # one residual block, as a unit
BLUR_W = 0.32                    # thickness of the G_sigma slab
PITCH = 0.55                     # gap between consecutive pics
DETAIL_H = 9.0                   # box height in the block-detail panel
DEPTH_F = 0.42                   # box depth as a fraction of height
TRUNK_PITCH = 1.0                # gap between blocks on the trunk
H_TO_CM = 0.28                   # drawn cm per unit of the pics' height
ROW_GAP = 2.3                    # clear space wanted between adjacent rows
ARC_RISE = 0.22                  # cm of clearance above a block box


GENERATED = ("%% generated by scripts/fig_arch_plotneuralnet.py -- do not edit\n"
             "%% Box/Ball pics: PlotNeuralNet (MIT), vendored in layers/\n")


def preamble():
    """Everything that must sit in the document preamble."""
    return (GENERATED
            + "%% \\input this in the paper preamble, before \\begin{document}.\n"
            + "\\providecommand{\\pnnDir}{}\n"
            "\\subimport{\\pnnDir layers/}{init}\n"
            "\\usetikzlibrary{positioning,3d,fit,backgrounds,calc}\n\n"
            "\\def\\ConvColor{rgb:yellow,5;red,2.5;white,5}\n"
            "\\def\\BlurColor{rgb:blue,6;green,1;white,3}\n"
            "\\def\\BlurEarlyColor{rgb:blue,6;green,2;white,2}\n"
            "\\def\\NormColor{rgb:white,6;black,1}\n"
            "\\def\\BlockColor{rgb:yellow,4;red,2;white,7}\n"
            "\\def\\FcColor{rgb:blue,5;red,2.5;white,5}\n"
            "\\def\\SumColor{rgb:blue,5;green,15}\n"
            "\\definecolor{bcred}{HTML}{D62728}\n"
            "\\definecolor{bcgrey}{HTML}{7A7A7A}\n")


def head():
    return (GENERATED
            + "\\begin{tikzpicture}\n"
            "\\tikzstyle{connection}=[ultra thick,every node/.style={sloped,"
            "allow upside down},draw=\\edgecolor,opacity=0.7]\n"
            "\\tikzstyle{skip}=[thick,draw={rgb:blue,4;red,1;green,1;black,3},"
            "opacity=0.6,-{Straight Barb[length=2mm]}]\n"
            "\\tikzset{sumop/.style={draw=black!65, fill=green!16, circle,"
            " inner sep=2.0pt, line width=0.7pt, font=\\normalsize}}\n"
            "\\tikzset{blockbg/.style={rounded corners=3pt, draw=black!30,"
            " fill=black!4, line width=0.4pt, inner sep=1.5mm}}\n"
            "\\tikzset{opnode/.style={rounded corners=1.5pt, draw=black!55,"
            " fill=black!5, line width=0.5pt, minimum height=5.5mm,"
            " minimum width=6.5mm, font=\\small}}\n")


def box(name, to, offset, h, w, channels, spatial, caption=" ", fill="\\ConvColor",
        zlabel=None, depth=None):
    """A PlotNeuralNet Box.  ``depth`` defaults to ``h``; a smaller value keeps
    the isometric footprint from swamping the horizontal spacing."""
    return (
        "\\pic[shift={%s}] at %s\n"
        "    {Box={name=%s, caption=%s, xlabel={{%s, }}, zlabel=%s,\n"
        "          fill=%s, height=%g, width=%g, depth=%g}};\n"
        % (offset, to, name, caption,
           "" if channels is None else channels,
           "" if zlabel is None else zlabel, fill, h, w,
           h if depth is None else depth))


def sigma_inset(x0, y0, w=5.2, h=2.3):
    """The sigma homotopy, drawn on the filter's own fixed support.

    The support never changes -- ``radius = ceil(truncate * sigma_max)`` fixes
    it at K taps for every sigma -- so the picture must show the bump narrowing
    inside a constant window, not the window shrinking.  Taps come from
    ``GaussianSmoothing.kernel``, the routine the model itself convolves with.
    """
    g = SiteController("gaussian").gauss
    rad = g.radius
    levels = []
    for v in GAUSSIAN["Gplateau"]:
        if v > 0 and (not levels or levels[-1] != v):
            levels.append(v)
    taps = {v: [float(t) for t in g.kernel(v)] for v in levels}
    peak = max(max(t) for t in taps.values())
    n = 2 * rad + 1
    dx = w / (n - 1)

    out = ["\n%% sigma homotopy on the filter's fixed support\n"]
    # the support, as a row of tap positions under a bracket
    out.append("\\draw[black!45, line width=0.4pt] (%g,%g) -- (%g,%g);\n"
               % (x0 - 0.15, y0, x0 + w + 0.15, y0))
    for i in range(n):
        out.append("\\draw[black!45, line width=0.4pt] (%g,%g) -- (%g,%g);\n"
                   % (x0 + i * dx, y0, x0 + i * dx, y0 - 0.09))
    out.append("\\draw[black!55, line width=0.5pt]\n"
               "  (%g,%g) -- (%g,%g) -- node[below, font=\\scriptsize,"
               " inner sep=2pt] {fixed $%d$-tap support, every $\\sigma$}\n"
               "  (%g,%g) -- (%g,%g);\n"
               % (x0, y0 - 0.26, x0, y0 - 0.42, n, x0 + w, y0 - 0.42,
                  x0 + w, y0 - 0.26))

    # one profile per plateau: lighter early (wide), darker late (narrow)
    for j, v in enumerate(levels):
        frac = 25 + 60 * j / max(1, len(levels) - 1)
        pts = " ".join("(%g,%g)" % (x0 + i * dx, y0 + taps[v][i] / peak * h)
                       for i in range(n))
        out.append("\\draw[bcred!%g, line width=%gpt] plot coordinates {%s};\n"
                   % (frac, 0.5 + 0.5 * (j == len(levels) - 1), pts))
    out.append("\\node[font=\\scriptsize, text=bcred, anchor=west] at "
               "(%g,%g) {$\\sigma=%.2f$};\n"
               % (x0 + w * 0.62, y0 + taps[levels[0]][rad] / peak * h + 0.12,
                  levels[0]))
    out.append("\\node[font=\\scriptsize, text=bcred, anchor=south east] at "
               "(%g,%g) {$\\sigma=%.2f$};\n"
               % (x0 + w / 2 - 0.18, y0 + h + 0.10, levels[-1]))

    # sigma = 0 is not a kernel at all: the tensor is returned unchanged
    out.append("\\draw[bcgrey, line width=0.9pt, dashed, "
               "dash pattern=on 1.1mm off 0.7mm]\n"
               "  (%g,%g) -- (%g,%g);\n"
               % (x0 + rad * dx, y0, x0 + rad * dx, y0 + h + 0.42))
    out.append("\\node[font=\\scriptsize, text=bcgrey, anchor=south west] at "
               "(%g,%g) {$\\sigma=0$};\n" % (x0 + rad * dx + 0.08, y0 + h + 0.42))
    out.append("\\node[font=\\scriptsize, align=center, text=bcred] at "
               "(%g,%g) {the filter narrows: $\\sigma = %.2f \\to %.2f$ over "
               "epochs $0$--$%d$\\\\{\\tiny then $\\sigma=0$ from epoch "
               "%d: an exact identity, no kernel applied}};\n"
               % (x0 + w / 2, y0 - 1.30, levels[0], levels[-1],
                  BYPASS_FROM - 1, BYPASS_FROM))
    return "".join(out)


def op_node(name, anchor, dx, label, style="opnode"):
    """GroupNorm / ReLU / addition: plain nodes, not PlotNeuralNet pics."""
    return ("\\node[%s] (%s) at ([shift={(%g,0,0)}] %s) {%s};\n"
            % (style, name, dx, anchor.strip("()"), label))


def sum_node(name, anchor, dx):
    """The residual addition, as a tikz node rather than a shaded Ball pic."""
    return ("\\node[sumop] (%s) at ([shift={(%g,0,0)}] %s) {$+$};\n"
            % (name, dx, anchor.strip("()")))


def main():
    out = [head()]
    site = 0

    # =================================================================
    # PANEL A -- what one residual block contains
    # =================================================================
    dy = 0.0
    h = DETAIL_H
    out.append(box("dc1", "(0,%g,0)" % dy, "(0,0,0)", h, 1.1, None, None,
                   caption=" ", fill="\\ConvColor", depth=h * DEPTH_F))
    out.append(box("dg1", "(dc1-east)", "(0.16,0,0)", h, BLUR_W, None, None,
                   caption=" ", fill="\\BlurColor", depth=h * DEPTH_F))
    out.append(op_node("dn1", "(dg1-east)", 0.85, "GN"))
    out.append(op_node("dr1", "(dn1.east)", 0.85, "$\\rho$"))
    out.append(box("dc2", "(dr1.east)", "(0.85,0,0)", h, 1.1, None, None,
                   caption=" ", fill="\\ConvColor", depth=h * DEPTH_F))
    out.append(box("dg2", "(dc2-east)", "(0.16,0,0)", h, BLUR_W, None, None,
                   caption=" ", fill="\\BlurColor", depth=h * DEPTH_F))
    out.append(op_node("dn2", "(dg2-east)", 0.85, "GN"))
    out.append(sum_node("dsum", "(dn2.east)", 0.85))
    out.append(op_node("dr2", "(dsum.east)", 0.85, "$\\rho$"))

    out.append("\\draw[connection] (-1.6,%g,0) -- node{\\midarrow} (dc1-west);\n" % dy)
    for a, b in (("dg1-east", "dn1.west"), ("dn1.east", "dr1.west"),
                 ("dr1.east", "dc2-west"), ("dg2-east", "dn2.west"),
                 ("dn2.east", "dsum.west"), ("dsum.east", "dr2.west")):
        out.append("\\draw[connection] (%s) -- (%s);\n" % (a, b))
    out.append("\\draw[connection] (dr2.east) -- node{\\midarrow} ++(1.4,0,0);\n")

    # the parameter-free shortcut
    ytop = dy + h * H_TO_CM / 2 + 0.35
    out.append("\\draw[skip] (-1.1,%g,0) -- (-1.1,%g)\n"
               "  -- (dsum.north |- 0,%g) -- (dsum.north);\n"
               % (dy, ytop, ytop))
    out.append("\\node[anchor=west, font=\\small, text=black!70] at "
               "(-1.0,%g,0) {shortcut: identity, or stride-2 subsample and "
               "zero-pad --- no convolution, so never hooked};\n"
               % (dy + h * H_TO_CM / 2 + 0.75))
    out.append("\\node[anchor=east, align=right, font=\\small] at "
               "(-1.8,%g,0) {\\textbf{one residual}\\\\\\textbf{block}"
               "\\\\[2pt]{\\footnotesize 2 of the \\nSitesTex{} "
               "sites}};\n" % dy)
    out.append("\\node[font=\\small, text=black!75] at "
               "(dg1-north) [above=1.5mm] {$G_\\sigma$};\n")
    out.append("\\node[font=\\small, text=black!75] at "
               "(dg2-north) [above=1.5mm] {$G_\\sigma$};\n")
    out.append("\\node[font=\\small, text=black!75] at "
               "(dc1-south) [below=3mm] {conv $3{\\times}3$};\n")
    out.append("\\node[font=\\small, text=black!75] at "
               "(dc2-south) [below=3mm] {conv $3{\\times}3$};\n")

    out.append(sigma_inset(11.4, dy - 1.15))

    # =================================================================
    # PANEL B -- the trunk, built by stacking those blocks
    # =================================================================
    ty = -(DETAIL_H * H_TO_CM / 2 + max(BOX_H.values()) * H_TO_CM / 2 + 3.2)
    out.append("\n%% trunk: one box per residual block, no sums on the line\n")

    stem_spatial = SITE_WIDTH_AT_32[0]
    out.append(box("cstem", "(0,%g,0)" % ty, "(0,0,0)", BOX_H[stem_spatial],
                   BOX_W[CHANNELS[0]], None, None, caption=" ",
                   fill="\\ConvColor", depth=BOX_H[stem_spatial] * DEPTH_F))
    out.append(box("gstem", "(cstem-east)", "(0.16,0,0)", BOX_H[stem_spatial],
                   BLUR_W, None, None, caption=" ", fill="\\BlurColor",
                   depth=BOX_H[stem_spatial] * DEPTH_F))
    out.append("\\node[font=\\small, align=center] at (cstem-south) "
               "[below=3mm] {stem\\\\[1pt]"
               "{\\footnotesize\\color{black!70}site $0$}};\n")
    site = 1
    prev = "(gstem-east)"

    trunk = ["gstem"]          # trunk elements, in order, for the arrows
    stages = []
    for stage, channels in enumerate(CHANNELS):
        spatial = SITE_WIDTH_AT_32[STAGE_OF_SITE.index(stage)]
        first_pic = None
        for b in range(BLOCKS_PER_STAGE):
            tag = "b%d%d" % (stage + 1, b + 1)
            out.append(box(tag, prev, "(%g,0,0)" % TRUNK_PITCH, BOX_H[spatial],
                           BLOCK_W[channels], None, None, caption=" ",
                           fill="\\BlockColor",
                           depth=BOX_H[spatial] * DEPTH_F))
            out.append("\\node[font=\\footnotesize, text=black!70] at "
                       "(%s-south) [below=3mm] {$%d,%d$};\n"
                       % (tag, site, site + 1))
            first_pic = first_pic or tag
            trunk.append(tag)
            prev = "(%s-east)" % tag
            site += 2
        stages.append((stage, spatial, channels, first_pic, tag))

    out.append(box("gap", prev, "(%g,0,0)" % (PITCH + 0.4), 3.0, 1.2,
                   None, None, caption="GAP", fill="\\NormColor"))
    out.append(box("fc", "(gap-east)", "(%g,0,0)" % (PITCH + 0.9), 2.4, 1.2,
                   10, None, caption="fc", fill="\\FcColor"))
    trunk += ["gap", "fc"]
    out.append("\\draw[connection] (-1.6,%g,0) -- node{\\midarrow} "
               "(cstem-west);\n" % ty)
    for a, b in zip(trunk, trunk[1:]):
        out.append("\\draw[connection] (%s-east) -- node{\\midarrow} "
                   "(%s-west);\n" % (a, b))
    out.append("\\draw[connection] (fc-east) -- node{\\midarrow} "
               "++(1.4,0,0);\n")

    # stage brackets, and the early7 span over the sites it covers
    yb = ty - max(BOX_H.values()) * H_TO_CM / 2 - 1.9
    for stage, spatial, channels, fp, lp in stages:
        s0 = 1 + stage * 2 * BLOCKS_PER_STAGE
        s1 = s0 + 2 * BLOCKS_PER_STAGE - 1
        out.append("\\draw[black!50, line width=0.5pt]\n"
                   "  (%s-west |- 0,%g) -- (%s-west |- 0,%g)\n"
                   "  -- node[below, font=\\small, inner sep=2.5pt,"
                   " align=center]\n"
                   "     {stage %d --- $%d{\\times}%d$, %d ch\\\\"
                   "{\\footnotesize sites $%d$--$%d$}}\n"
                   "  (%s-east |- 0,%g) -- (%s-east |- 0,%g);\n"
                   % (fp, yb + 0.45, fp, yb, stage + 1, spatial, spatial,
                      channels, s0, s1, lp, yb, lp, yb + 0.45))

    ye = ty + max(BOX_H.values()) * H_TO_CM / 2 + 0.6
    out.append("\\draw[black!55, line width=0.5pt]\n"
               "  (cstem-west |- 0,%g) -- (cstem-west |- 0,%g)\n"
               "  -- node[above, font=\\small, inner sep=2pt]\n"
               "     {\\texttt{early7}: only these \\nEarlyTex{} sites are "
               "filtered}\n"
               "  (b13-east |- 0,%g) -- (b13-east |- 0,%g);\n"
               % (ye, ye + 0.4, ye + 0.4, ye))

    # =================================================================
    # legend
    # =================================================================
    out.append("\n%% legend\n")
    kern = SiteController("gaussian").describe()["gaussian_kernel"]
    ks, rad = kern["kernel_size"], kern["radius"]
    stage_w = [SITE_WIDTH_AT_32[STAGE_OF_SITE.index(st)]
               for st in range(len(CHANNELS))]
    cov = " / ".join("%.0f\\%%" % (100.0 * ks / w) for w in stage_w)
    chans = " / ".join(str(c) for c in CHANNELS)
    widths = " / ".join("$%d{\\times}%d$" % (w, w) for w in stage_w)

    ky = yb - 2.6
    out.append("\\pic[shift={(0,0,0)}] at (-0.2,%g,0)\n"
               "    {Box={name=kconv, caption= , xlabel={{, }}, zlabel= ,\n"
               "          fill=\\ConvColor, height=2.2, width=1.6, depth=2.2}};\n"
               % ky)
    out.append("\\node[anchor=west, align=left, font=\\small] at (1.0,%g,0)\n"
               "  {conv $3{\\times}3$, no bias\\\\[1pt]"
               "{\\footnotesize %s channels at stages 1 / 2 / 3, "
               "on maps of %s}};\n" % (ky, chans, widths))
    out.append("\\pic[shift={(0,0,0)}] at (-0.2,%g,0)\n"
               "    {Box={name=kblur, caption= , xlabel={{, }}, zlabel= ,\n"
               "          fill=\\BlurColor, height=2.2, width=0.55, depth=2.2}};\n"
               % (ky - 1.7))
    out.append("\\node[anchor=west, align=left, font=\\small] at (1.0,%g,0)\n"
               "  {$G_\\sigma$ insertion, \\nSitesTex{} of them\\\\[1pt]"
               "{\\footnotesize separable, depthwise, reflection-padded; "
               "one fixed ${%d}{\\times}{%d}$ support (radius $%d$) for every "
               "$\\sigma$}\\\\[1pt]"
               "{\\footnotesize that support spans %s of the map width at "
               "stages 1 / 2 / 3}};\n"
               % (ky - 1.7, ks, ks, rad, cov))
    out.append("\\pic[shift={(0,0,0)}] at (-0.2,%g,0)\n"
               "    {Box={name=kblk, caption= , xlabel={{, }}, zlabel= ,\n"
               "          fill=\\BlockColor, height=2.2, width=1.6, depth=2.2}};\n"
               % (ky - 3.8))
    out.append("\\node[anchor=west, align=left, font=\\small] at (1.0,%g,0)\n"
               "  {one residual block, drawn above\\\\[1pt]"
               "{\\footnotesize two hooked convolutions and one shortcut; "
               "the numbers beneath give its two site indices}};\n"
               % (ky - 3.8))
    out.append("\\node[anchor=west, font=\\small] at (-0.9,%g,0)\n"
               "  {insertion mask --- \\texttt{all19}: every site is "
               "filtered; \\texttt{early7}: only sites $0$--$\\earlyLastTex$ "
               "are, and the $12$ deeper sites run unfiltered};\n"
               % (ky - 5.6))
    out.append("\\node[anchor=west, font=\\small] at (-0.9,%g,0)\n"
               "  {both names are campaign configuration tokens, as in "
               "\\texttt{R32\\_\\_Gplateau\\_\\_input\\_bilinear\\_\\_all19}};"
               "\n" % (ky - 6.6))

    CAP.write_text(
        GENERATED
        + "%% The legend as prose, for \\caption{} instead of in the picture.\n"
        + "ResNet-20-GN with the %d Gaussian insertion sites. Above: one "
          "residual block, conv $\\to$ $G_\\sigma$ $\\to$ GN $\\to$ "
          "$\\rho$ $\\to$ conv $\\to$ $G_\\sigma$ $\\to$ GN $\\to$ $+$ "
          "$\\to$ $\\rho$; the forward hook rewrites each convolution's "
          "output, before GroupNorm and before the ReLU, and the shortcut "
          "carries no convolution so it is never hooked. Below: the network, "
          "stacked from those blocks --- a stem (site $0$) and nine blocks "
          "(two sites each), %s channels at stages 1 / 2 / 3 on maps of %s. "
          "The filter is separable, depthwise and reflection-padded, with one "
          "fixed $%d{\\times}%d$ support (radius $%d$) for every $\\sigma$; "
          "that support spans %s of the map width at stages 1 / 2 / 3. "
          "Insertion mask \\texttt{all19} filters every site; "
          "\\texttt{early7} filters only sites $0$--$%d$, leaving the %d "
          "deeper sites unfiltered.\n"
          % (N_SITES, chans, widths, ks, ks, rad, cov, EARLY7[-1],
             N_SITES - len(EARLY7)))

    PRE.write_text(preamble()
                   + "\\newcommand{\\nSitesTex}{%d}\n" % N_SITES
                   + "\\newcommand{\\nEarlyTex}{%d}\n" % len(EARLY7)
                   + "\\newcommand{\\earlyLastTex}{%d}\n" % EARLY7[-1])
    OUT.write_text("".join(out) + "\n\\end{tikzpicture}\n")
    print("sites accounted for:", site, "(expected %d)" % N_SITES)
    assert site == N_SITES, (site, N_SITES)
    print("wrote", PRE)
    print("wrote", CAP)
    print("wrote", OUT)
    print("bypass epoch %d of %d" % (BYPASS_FROM, EPOCHS))


if __name__ == "__main__":
    main()
