"""Run a local Python script on Kaggle's remote compute (CPU or GPU) and pull results back.

    py scripts/kaggle_run.py path/to/job.py --gpu

Wraps ``kaggle kernels push/status/output``: packages the script as a private
Kaggle "script" kernel, pushes it, polls until it finishes, then downloads the
kernel log and any files the script wrote to ``/kaggle/working`` into a local
output folder.

Controls that make remote runs reproducible and non-destructive:

* **Repo shipping.**  Kaggle script kernels accept a single code file, so the
  requested packages (default: ``continuation``) are zipped, embedded in the
  generated wrapper and unpacked on the worker before the job runs.  Jobs can
  therefore ``import continuation`` instead of carrying an inlined -- and
  silently diverging -- copy of the code.
* **Provenance.**  The wrapper always writes ``environment.json`` (python,
  platform, torch/CUDA versions, whether a GPU was *actually* granted, its name
  and VRAM) next to the job's own outputs.  Accelerator availability and quota
  are never assumed; they are recorded from the worker.
* **No clobbering.**  The kernel slug and the local output directory carry a run
  tag, and a non-empty output directory is refused unless ``--overwrite``.
* **Logs on failure.**  Output and log are pulled before any error is raised.
* **Internet is off by default** and must be requested explicitly.

Requires the ``kaggle`` CLI on PATH and ``~/.kaggle/kaggle.json`` for auth (see
docs/kaggle_cli.md).
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import re
import shutil
import subprocess
import sys
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
JOBS_DIR = REPO_ROOT / "kaggle_jobs"
DEFAULT_INCLUDES = ("continuation",)
MAX_SOURCE_BYTES = 900_000          # Kaggle rejects very large kernel sources

_TERMINAL_OK = ("complete",)
_TERMINAL_BAD = ("error", "cancel", "fail")


def _kaggle_username() -> str:
    cfg = Path.home() / ".kaggle" / "kaggle.json"
    return json.loads(cfg.read_text())["username"]


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "job"


def _kaggle_cmd():
    """Resolve the Kaggle CLI.

    ``kaggle`` is frequently installed into a Scripts/bin directory that is not
    on PATH for every shell, so fall back to the console script next to the
    running interpreter and finally to ``python -m kaggle``.
    """
    found = shutil.which("kaggle")
    if found:
        return [found]
    for sub in ("Scripts/kaggle.exe", "bin/kaggle"):
        cand = Path(sys.executable).parent / sub
        if cand.exists():
            return [str(cand)]
        cand = Path(sys.prefix) / sub
        if cand.exists():
            return [str(cand)]
    return [sys.executable, "-m", "kaggle"]


_KAGGLE = None


def _run(cmd, **kwargs):
    global _KAGGLE
    if cmd and cmd[0] == "kaggle":
        if _KAGGLE is None:
            _KAGGLE = _kaggle_cmd()
        cmd = _KAGGLE + cmd[1:]
    print(f"$ {' '.join(cmd)}", flush=True)
    return subprocess.run(cmd, text=True, capture_output=True, **kwargs)


def _zip_includes(includes) -> bytes:
    """Zip the requested files/dirs (repo-relative), skipping caches."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for item in includes:
            src = (REPO_ROOT / item).resolve()
            if not src.exists():
                raise FileNotFoundError(f"--include path not found: {item}")
            if src.is_file():
                zf.write(src, src.relative_to(REPO_ROOT).as_posix())
                continue
            for p in sorted(src.rglob("*")):
                if not p.is_file() or "__pycache__" in p.parts or p.suffix == ".pyc":
                    continue
                zf.write(p, p.relative_to(REPO_ROOT).as_posix())
    return buf.getvalue()


_WRAPPER = '''# Auto-generated by scripts/kaggle_run.py -- do not edit.
import base64, io, json, os, platform, runpy, sys, zipfile

WORK = "/kaggle/working"
os.makedirs(WORK, exist_ok=True)

# --- unpack the shipped repo subset so the job can import it normally ---
_PAYLOAD = "{payload}"
_repo = os.path.join(WORK, "_repo")
if _PAYLOAD:
    os.makedirs(_repo, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(base64.b64decode(_PAYLOAD))) as zf:
        zf.extractall(_repo)
    sys.path.insert(0, _repo)

# --- provenance: never assume an accelerator was granted ---
env = {{
    "python": sys.version.split()[0],
    "platform": platform.platform(),
    "requested_gpu": {requested_gpu},
    "shipped": {shipped!r},
}}
try:
    import torch
    env.update(torch=torch.__version__,
               cuda_version=torch.version.cuda,
               cudnn=torch.backends.cudnn.version(),
               cuda_available=bool(torch.cuda.is_available()))
    if torch.cuda.is_available():
        p = torch.cuda.get_device_properties(0)
        env.update(gpu_name=p.name,
                   gpu_total_vram_mib=round(p.total_memory / 1024 ** 2),
                   gpu_capability="%d.%d" % (p.major, p.minor))
except Exception as exc:
    env["torch_error"] = repr(exc)
with open(os.path.join(WORK, "environment.json"), "w") as fh:
    json.dump(env, fh, indent=2)
print("ENVIRONMENT " + json.dumps(env), flush=True)

runpy.run_path(os.path.join(_repo, {job_rel!r}) if _PAYLOAD else "job.py",
               run_name="__main__")
'''


def build_source(script_path: Path, includes, gpu: bool) -> tuple:
    """Return (wrapper source, shipped file list)."""
    rel = None
    try:
        rel = script_path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        pass
    items = list(includes)
    if rel is None:
        raise ValueError("the job script must live inside the repo so it can be shipped")
    if not any(rel == i or rel.startswith(i.rstrip("/") + "/") for i in items):
        items.append(rel)
    blob = _zip_includes(items)
    payload = base64.b64encode(blob).decode("ascii")
    with zipfile.ZipFile(io.BytesIO(blob)) as zf:
        shipped = zf.namelist()
    src = _WRAPPER.format(payload=payload, requested_gpu=bool(gpu),
                          shipped=len(shipped), job_rel=rel)
    if len(src.encode("utf-8")) > MAX_SOURCE_BYTES:
        raise ValueError(
            "packaged source is %.0f kB, over the %.0f kB limit; pass fewer "
            "--include paths" % (len(src) / 1000, MAX_SOURCE_BYTES / 1000))
    return src, shipped


def push_and_run(script_path: Path, *, gpu: bool = False, internet: bool = False,
                 title: str | None = None, includes=DEFAULT_INCLUDES,
                 poll_seconds: int = 20, timeout_seconds: int = 3600,
                 tag: str | None = None, overwrite: bool = False,
                 dry_run: bool = False, datasets=(), accelerator=None) -> Path:
    username = _kaggle_username()
    base = title or script_path.stem
    run_tag = tag or datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    slug = _slugify(f"{base}-{run_tag}")
    kernel_id = f"{username}/{slug}"

    output_dir = REPO_ROOT / "results" / "kaggle_outputs" / slug
    if output_dir.exists() and any(output_dir.iterdir()) and not overwrite:
        raise FileExistsError(
            f"{output_dir} is not empty; pass --overwrite to replace it "
            "(outputs are tagged per run so this should be rare)")

    source, shipped = build_source(script_path, includes, gpu)
    job_dir = JOBS_DIR / slug
    job_dir.mkdir(parents=True, exist_ok=True)
    (job_dir / "script.py").write_text(source, encoding="utf-8")
    metadata = {
        "id": kernel_id, "title": slug, "code_file": "script.py",
        "language": "python", "kernel_type": "script", "is_private": True,
        "enable_gpu": gpu, "enable_internet": internet, "enable_tpu": False,
        # machine_shape IS the accelerator selector: kernels_push sets
        # request.machine_shape = acc or metadata["machine_shape"].  Leaving it
        # unset makes Kaggle fall back to a generic "Gpu" shape.
        "machine_shape": accelerator or "",
        "dataset_sources": list(datasets), "kernel_sources": [],
        "competition_sources": [],
    }
    (job_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))

    print(f"kernel   : {kernel_id}")
    print(f"gpu      : {gpu}   internet: {internet}   accelerator: {accelerator or '(default)'}")
    print(f"shipped  : {len(shipped)} files ({', '.join(sorted(includes))})")
    print(f"datasets : {list(datasets) or 'none'}")
    print(f"source   : {len(source) / 1000:.0f} kB")
    print(f"outputs  : {output_dir}")
    if dry_run:
        print("dry run - nothing pushed")
        return output_dir

    push_cmd = ["kaggle", "kernels", "push", "-p", str(job_dir)]
    if accelerator:
        push_cmd += ["--accelerator", accelerator]
    push = _run(push_cmd)
    print(push.stdout)
    if push.returncode != 0:
        print(push.stderr, file=sys.stderr)
        raise RuntimeError("kaggle kernels push failed")

    print(f"polling every {poll_seconds}s (timeout {timeout_seconds}s)...", flush=True)
    deadline = time.time() + timeout_seconds
    status = ""
    ok = False
    while time.time() < deadline:
        status = _run(["kaggle", "kernels", "status", kernel_id]).stdout.strip()
        print(status, flush=True)
        low = status.lower()
        if any(t in low for t in _TERMINAL_OK):
            ok = True
            break
        if any(t in low for t in _TERMINAL_BAD):
            break
        time.sleep(poll_seconds)

    # Always try to retrieve outputs and log, including for failed runs.
    output_dir.mkdir(parents=True, exist_ok=True)
    pull = _run(["kaggle", "kernels", "output", kernel_id, "-p", str(output_dir)])
    print(pull.stdout or pull.stderr)
    # "kernels output" already retrieves the run log; no separate call needed.

    if not ok:
        raise RuntimeError(
            f"kernel {kernel_id} did not complete (last status: {status!r}); "
            f"any log/output retrieved is in {output_dir}")
    print(f"Done. Outputs in {output_dir}")
    return output_dir


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("script", type=Path, help="local .py file (inside the repo) to run")
    p.add_argument("--gpu", action="store_true", help="request a Kaggle GPU accelerator")
    p.add_argument("--internet", action="store_true",
                   help="enable internet in the kernel (off by default)")
    p.add_argument("--include", action="append", default=None,
                   help="repo-relative file/dir to ship (repeatable; default: continuation)")
    p.add_argument("--title", help="base name for the kernel slug (default: script stem)")
    p.add_argument("--tag", help="run tag appended to the slug (default: UTC timestamp)")
    p.add_argument("--overwrite", action="store_true",
                   help="allow replacing a non-empty local output directory")
    p.add_argument("--accelerator", default=None,
                   help="accelerator id for machine_shape, e.g. NvidiaTeslaT4")
    p.add_argument("--dataset", action="append", default=None,
                   help="Kaggle dataset ref to attach, e.g. owner/slug (repeatable)")
    p.add_argument("--dry-run", action="store_true",
                   help="package and report, but do not push")
    p.add_argument("--poll-seconds", type=int, default=20)
    p.add_argument("--timeout-seconds", type=int, default=3600)
    args = p.parse_args()

    if not args.script.exists():
        p.error(f"script not found: {args.script}")

    push_and_run(args.script, gpu=args.gpu, internet=args.internet,
                 title=args.title, includes=tuple(args.include or DEFAULT_INCLUDES),
                 poll_seconds=args.poll_seconds, timeout_seconds=args.timeout_seconds,
                 tag=args.tag, overwrite=args.overwrite, dry_run=args.dry_run,
                 datasets=tuple(args.dataset or ()), accelerator=args.accelerator)


if __name__ == "__main__":
    main()
