"""Publish inputs and run the three evaluation jobs on three Kaggle accounts.

    py -m landscape_study.kaggle publish --accounts maxnicaise maxlefrr maxnikezz
    py -m landscape_study.kaggle push --job 0 --account maxnicaise
    py -m landscape_study.kaggle status --job 0 --account maxnicaise
    py -m landscape_study.kaggle pull --job 0 --account maxnicaise

``publish`` creates a **private** dataset ``<account>/landscape-v1-inputs`` from
``studies/landscape_v1/inputs`` (a private dataset is only visible to its owner,
so each account gets its own copy).  ``push`` ships ``continuation_core`` and
``landscape_study`` zipped inside a private script kernel (T4, internet off),
attaching CIFAR-10 (``pankrzysiu/cifar10-python``) and the inputs dataset; the
job verifies every input digest before evaluating.  Same mechanism as
``scripts/kaggle_run.py`` on ``benchmark-organized``.  Credentials stay in
``~/.kaggle-accounts/<name>/`` and are never copied.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import os
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ROOT / "studies" / "landscape_v1" / "inputs"
STAGE = ROOT / "studies" / "landscape_v1" / "kaggle_stage"
RESULTS = ROOT / "studies" / "landscape_v1" / "results"
SLUG = "landscape-v1-inputs"
CIFAR = "pankrzysiu/cifar10-python"

WRAPPER = '''# generated by landscape_study/kaggle.py
import base64, io, os, subprocess, sys, zipfile
WORK = "/kaggle/working"
repo = os.path.join(WORK, "_repo")
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
out = os.path.join(WORK, "job{job}")
r = subprocess.run([sys.executable, "-m", "landscape_study.run", "--job", "{job}",
                    "--out", out], cwd=repo)
sys.exit(r.returncode)
'''


def env_for(account):
    cfg = Path.home() / ".kaggle-accounts" / account
    if not (cfg / "kaggle.json").is_file():
        raise SystemExit("no credentials for account %r" % account)
    return {**os.environ, "KAGGLE_CONFIG_DIR": str(cfg)}, json.loads((cfg / "kaggle.json").read_text())["username"]


def run(cmd, env):
    print("$ " + " ".join(cmd), flush=True)
    r = subprocess.run([shutil.which("kaggle") or "kaggle"] + cmd[1:], text=True,
                       capture_output=True, env=env, encoding="utf-8", errors="replace")
    print((r.stdout or "") + (r.stderr or ""), flush=True)
    return r


def publish(accounts):
    for acc in accounts:
        env, user = env_for(acc)
        if STAGE.exists():
            shutil.rmtree(STAGE)
        shutil.copytree(INPUTS, STAGE)
        ref = "%s/%s" % (user, SLUG)
        (STAGE / "dataset-metadata.json").write_text(json.dumps(
            {"title": "landscape v1 inputs", "id": ref, "licenses": [{"name": "unknown"}]}, indent=2))
        exists = run(["kaggle", "datasets", "status", ref], env).returncode == 0
        cmd = (["kaggle", "datasets", "version", "-p", str(STAGE), "-m", "inputs", "-r", "zip"]
               if exists else ["kaggle", "datasets", "create", "-p", str(STAGE), "-r", "zip"])
        if run(cmd, env).returncode != 0:
            raise SystemExit("dataset publish failed for %s" % acc)


def payload():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "landscape_study"):
            for p in sorted((ROOT / pkg).rglob("*.py")):
                zf.write(p, p.relative_to(ROOT).as_posix())
    return base64.b64encode(buf.getvalue()).decode("ascii")


def kernel_id(job, account):
    _, user = env_for(account)
    return "%s/landscape-v1-job%s" % (user, job)


def push(job, account):
    env, user = env_for(account)
    d = STAGE.parent / ("kernel_job%s" % job)
    d.mkdir(parents=True, exist_ok=True)
    (d / "script.py").write_text(WRAPPER.format(payload=payload(), job=job), encoding="utf-8")
    kid = kernel_id(job, account)
    (d / "kernel-metadata.json").write_text(json.dumps({
        "id": kid, "title": "landscape-v1-job%s" % job, "code_file": "script.py",
        "language": "python", "kernel_type": "script", "is_private": True,
        "enable_gpu": True, "enable_internet": False, "enable_tpu": False,
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": [CIFAR, "%s/%s" % (user, SLUG)],
        "kernel_sources": [], "competition_sources": []}, indent=2))
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / ("launch_job%s.json" % job)).write_text(json.dumps(
        {"account": account, "kernel_id": kid, "launched_utc": datetime.now(timezone.utc).isoformat()},
        indent=2))
    if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
        raise SystemExit("push failed")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("action", choices=("publish", "push", "status", "pull"))
    ap.add_argument("--accounts", nargs="*", default=[])
    ap.add_argument("--account")
    ap.add_argument("--job")
    a = ap.parse_args()
    if a.action == "publish":
        publish(a.accounts)
    elif a.action == "push":
        push(a.job, a.account)
    elif a.action == "status":
        run(["kaggle", "kernels", "status", kernel_id(a.job, a.account)], env_for(a.account)[0])
    else:
        out = RESULTS / ("kaggle_job%s" % a.job)
        out.mkdir(parents=True, exist_ok=True)
        run(["kaggle", "kernels", "output", kernel_id(a.job, a.account), "-p", str(out)],
            env_for(a.account)[0])


if __name__ == "__main__":
    main()
