"""Publish per-account inputs, push jobs (tasks inside the code payload), pull, verify.

    py -m landscape_v3.kaggle publish [--accounts ...]
    py -m landscape_v3.kaggle push [--accounts ...] [--pilot]
    py -m landscape_v3.kaggle status
    py -m landscape_v3.kaggle pull --account maxnicaise [--pilot]
    py -m landscape_v3.kaggle verify --account maxnicaise [--pilot]

Dataset ``landscape-v3-inputs`` per account (flat): the checkpoints its tasks need
(``<method>__seed<k>__epoch_NNN.pt``, byte copies of the v2 files), the v2
direction draw files of its seeds, ``subsets.npz`` and ``expected_digests.json``.
Kernel ``landscape-v3-<account>`` (``-pilot`` suffix for the pilot).  ``verify``
recomputes the sha256 of every file listed in ``eval_manifest.json``; the
downloader's exit code is never taken as evidence.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import shutil
import zipfile
from datetime import datetime, timezone

from landscape_v2.kaggle import env_for, run

from . import common as C

PROTO = C.STUDY / "protocol"
STAGE = C.STUDY / "kaggle_stage"
RAW = C.STUDY / "raw"
SLUG = "landscape-v3-inputs"

WRAPPER = '''# generated by landscape_v3/kaggle.py
import base64, io, os, subprocess, sys, zipfile
repo = "/kaggle/working/_repo"
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
args = [sys.executable, "-m", "landscape_v3.run", "--tasks", os.path.join(repo, "tasks.json"),
        "--out", "/kaggle/working/v3", "--deadline-hours", "{hours}"] + {extra}
r = subprocess.run(args, cwd=repo)
sys.exit(r.returncode)
'''


def bundle(acc, pilot):
    return json.loads((PROTO / ("%s_%s.json" % ("pilot" if pilot else "bundle", acc))).read_text())


def needed_files(acc):
    if not (PROTO / ("bundle_%s.json" % acc)).exists():
        return [], []
    b = bundle(acc, False)
    cks, seeds = set(), set()
    for t in b["tasks"]:
        seeds.add(t["s"])
        cks.add("%s__%s" % (C.rname(t["m"], t["s"]), t.get("ckpt", C.FINAL)))
    return sorted(cks), sorted(seeds)


def publish(accounts):
    dig = json.loads((PROTO / "expected_digests.json").read_text())
    for acc in accounts:
        d = STAGE / acc
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True)
        cks, seeds = needed_files(acc)
        for f in cks:
            rname, ep = f.split("__epoch_")
            m, s = rname.rsplit("__seed", 1)
            src = C.v2_run_dir(m, int(s)) / "checkpoints" / ("epoch_" + ep)
            shutil.copy2(src, d / f)
            assert C.sha_file(d / f) == dig["checkpoints"][f], f
        for s in seeds:
            for k in range(C.N_DIRECTIONS):
                shutil.copy2(C.V2_RAW / C.V2_ACCOUNT_OF_SEED[s] / "v2" / "directions" / ("seed%d_dir%02d.pt" % (s, k)),
                             d / ("seed%d_dir%02d.pt" % (s, k)))
        shutil.copy2(C.V2_STUDY / "inputs" / "subsets.npz", d / "subsets.npz")
        shutil.copy2(PROTO / "expected_digests.json", d / "expected_digests.json")
        env, user = env_for(acc)
        (d / "dataset-metadata.json").write_text(json.dumps(
            {"title": "landscape v3 inputs", "id": "%s/%s" % (user, SLUG), "licenses": [{"name": "unknown"}]}))
        print(acc, len(cks), "checkpoints", seeds, flush=True)
        r = run(["kaggle", "datasets", "create", "-p", str(d)], env)
        txt = (r.stdout or "") + (r.stderr or "")
        if r.returncode or "already" in txt.lower() or "error" in txt.lower():
            r = run(["kaggle", "datasets", "version", "-p", str(d), "-m", "landscape_v3 reassignment"], env)
            if r.returncode:
                raise SystemExit("publish failed for %s" % acc)


def payload(acc, pilot):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "landscape_study", "landscape_v2", "landscape_v3"):
            for p in sorted((C.ROOT / pkg).rglob("*.py")):
                zf.write(p, p.relative_to(C.ROOT).as_posix())
        zf.writestr("tasks.json", json.dumps(bundle(acc, pilot)))
    return base64.b64encode(buf.getvalue()).decode("ascii")


def kid(acc, pilot=False):
    return "%s/landscape-v3-%s%s" % (env_for(acc)[1], acc.lower(), "-pilot" if pilot else "")


def push(accounts, hours, pilot):
    for acc in accounts:
        env, user = env_for(acc)
        d = STAGE / ("kernel_%s%s" % (acc, "_pilot" if pilot else ""))
        d.mkdir(parents=True, exist_ok=True)
        extra = '["--pilot"]' if pilot else "[]"
        (d / "script.py").write_text(WRAPPER.format(payload=payload(acc, pilot), hours=hours, extra=extra),
                                     encoding="utf-8")
        (d / "kernel-metadata.json").write_text(json.dumps({
            "id": kid(acc, pilot), "title": "landscape-v3-%s%s" % (acc.lower(), "-pilot" if pilot else ""),
            "code_file": "script.py", "language": "python", "kernel_type": "script", "is_private": True,
            "enable_gpu": True, "enable_internet": False, "enable_tpu": False, "machine_shape": "NvidiaTeslaT4",
            "dataset_sources": ["pankrzysiu/cifar10-python", "%s/%s" % (user, SLUG)],
            "kernel_sources": [], "competition_sources": []}, indent=2))
        RAW.mkdir(parents=True, exist_ok=True)
        (RAW / ("launch_%s%s.json" % (acc, "_pilot" if pilot else ""))).write_text(json.dumps(
            {"account": acc, "kernel": kid(acc, pilot), "pilot": pilot,
             "launched_utc": datetime.now(timezone.utc).isoformat(),
             "script_bytes": (d / "script.py").stat().st_size}, indent=2))
        print(acc, "script bytes", (d / "script.py").stat().st_size, flush=True)
        if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
            raise SystemExit("push failed for %s" % acc)


def verify(acc, pilot):
    import hashlib
    root = RAW / (acc + ("_pilot" if pilot else "")) / "v3"
    rep = {"account": acc, "pilot": pilot}
    p = root / "eval_manifest.json"
    if not p.exists():
        rep["eval_manifest"] = "MISSING MANIFEST"
    else:
        listed = json.loads(p.read_text())
        missing, bad = [], []
        for rel, info in listed.items():
            f = root / rel
            if not f.exists():
                missing.append(rel)
                continue
            if hashlib.sha256(f.read_bytes()).hexdigest() != info["sha256"] or f.stat().st_size != info["bytes"]:
                bad.append(rel)
        rep["eval_manifest"] = {"listed": len(listed), "missing": missing, "hash_mismatch": bad}
    (RAW / ("verify_%s%s.json" % (acc, "_pilot" if pilot else ""))).write_text(json.dumps(rep, indent=2))
    em = rep["eval_manifest"]
    print(acc, em if isinstance(em, str) else {k: (len(v) if isinstance(v, list) else v) for k, v in em.items()})
    return rep


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("action", choices=("publish", "push", "status", "pull", "verify"))
    ap.add_argument("--accounts", nargs="*", default=list(C.ACCOUNTS))
    ap.add_argument("--account")
    ap.add_argument("--hours", default="11.3")
    ap.add_argument("--pilot", action="store_true")
    a = ap.parse_args()
    accs = [a.account] if a.account else a.accounts
    if a.action == "publish":
        publish(accs)
    elif a.action == "push":
        push(accs, a.hours, a.pilot)
    elif a.action == "status":
        for acc in accs:
            run(["kaggle", "kernels", "status", kid(acc, a.pilot)], env_for(acc)[0])
    elif a.action == "pull":
        for acc in accs:
            dest = RAW / (acc + ("_pilot" if a.pilot else ""))
            dest.mkdir(parents=True, exist_ok=True)
            run(["kaggle", "kernels", "output", kid(acc, a.pilot), "-p", str(dest), "-o"], env_for(acc)[0])
    else:
        for acc in accs:
            verify(acc, a.pilot)


if __name__ == "__main__":
    main()
