"""Publish inputs, push shards, poll, pull and verify, on the six allocated accounts only.

    py -m comparison.kaggle publish [--accounts ...]
    py -m comparison.kaggle push --tag pilot --accounts maxfrrsava
    py -m comparison.kaggle push --tag main [--accounts ...]
    py -m comparison.kaggle status --tag main
    py -m comparison.kaggle pull --tag main [--accounts ...]
    py -m comparison.kaggle verify --tag main [--accounts ...]

Per account, dataset ``<user>/cbs-sdpoint-inputs``: the pinned asset set (``assets/``), for SGD
shards the four reused landscape_v2 endpoints of that seed (``reused/<run>/epoch_030.pt``,
``config.json``, ``summary.json``, ``metrics.json``) and ``inputs_manifest.json`` (sha256 of
every file).  Code travels inside the kernel script.  ``maxmonstre`` is refused.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from . import matrix as MX

STAGE = MX.STUDY / "kaggle_stage"
RAW = MX.STUDY / "raw"
SLUG = "cbs-sdpoint-inputs"
V2 = MX.ROOT.parent / "visualization" / "studies" / "landscape_v2" / "raw"

WRAPPER = '''# generated by comparison/kaggle.py
import base64, io, os, subprocess, sys, zipfile
repo = "/kaggle/working/_repo"
os.makedirs(repo, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{payload}"))) as zf:
    zf.extractall(repo)
args = [sys.executable, "-m", "comparison.job", "--setting", "{setting}", "--seeds"] + {seeds} + [
        "--out", "/kaggle/working/cmp"] + {extra}
r = subprocess.run(args, cwd=repo)
sys.exit(r.returncode)
'''


def env_for(acc):
    if acc == MX.RESERVED_ACCOUNT:
        raise SystemExit("%s is reserved for the geometry study" % acc)
    cfg = Path.home() / ".kaggle-accounts" / acc
    user = json.loads((cfg / "kaggle.json").read_text())["username"]
    import os
    return {**os.environ, "KAGGLE_CONFIG_DIR": str(cfg)}, user


def run(cmd, env):
    exe = shutil.which("kaggle") or "kaggle"
    r = subprocess.run([exe] + cmd[1:], text=True, capture_output=True, env=env, encoding="utf-8", errors="replace")
    print("$ " + " ".join(cmd) + "\n" + ((r.stdout or "") + (r.stderr or ""))[-1500:], flush=True)
    return r


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def publish(accounts):
    for acc in accounts:
        setting, seeds = MX.SHARDS[acc]
        d = STAGE / ("inputs_" + acc)
        if d.exists():
            shutil.rmtree(d)
        (d / "assets").mkdir(parents=True)
        for f in (MX.ROOT / "assets" / "cifar10_resnet20bn").iterdir():
            shutil.copy2(f, d / "assets" / f.name)
        man = {"files": {}, "reused": {}}
        for seed in (seeds if setting == "sgd" else ()):
            for arm in MX.HISTORICAL:
                src = V2 / MX.V2_ACCOUNT[seed] / "v2" / "runs" / ("%s__seed%d" % (arm, seed))
                run_name = "sgd__%s__seed%d" % (arm, seed)
                dst = d / "reused" / run_name
                dst.mkdir(parents=True)
                shutil.copy2(src / "checkpoints" / "epoch_030.pt", dst / "epoch_030.pt")
                for f in ("config.json", "summary.json", "metrics.json"):
                    shutil.copy2(src / f, dst / f)
                rm = json.loads((V2 / MX.V2_ACCOUNT[seed] / "v2" / "runs_manifest.json").read_text())
                want = rm["runs/%s__seed%d/checkpoints/epoch_030.pt" % (arm, seed)]["sha256"]
                got = sha(dst / "epoch_030.pt")
                assert got == want, (run_name, got, want)
                man["reused"][run_name] = {"source": "visualization worktree studies/landscape_v2/raw/%s/v2/runs/%s__seed%d"
                                           % (MX.V2_ACCOUNT[seed], arm, seed),
                                           "checkpoint_sha256": got, "runs_manifest_sha256": want}
        for p in sorted(d.rglob("*")):
            if p.is_file():
                man["files"][p.relative_to(d).as_posix()] = {"sha256": sha(p), "bytes": p.stat().st_size}
        (d / "inputs_manifest.json").write_text(json.dumps(man, indent=1))
        env, user = env_for(acc)
        (d / "dataset-metadata.json").write_text(json.dumps({"title": "cbs sdpoint inputs", "id": "%s/%s" % (user, SLUG),
                                                             "licenses": [{"name": "unknown"}]}))
        r = run(["kaggle", "datasets", "create", "-p", str(d), "--dir-mode", "zip"], env)
        txt = (r.stdout or "") + (r.stderr or "")
        if r.returncode or "already" in txt.lower() or "error" in txt.lower():
            r = run(["kaggle", "datasets", "version", "-p", str(d), "-m", "inputs", "--dir-mode", "zip"], env)
            if r.returncode:
                raise SystemExit("publish failed for %s" % acc)


def payload():
    buf, files = io.BytesIO(), []
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for pkg in ("continuation_core", "comparison", "tests"):
            for p in sorted((MX.ROOT / pkg).rglob("*.py")):
                rel = p.relative_to(MX.ROOT).as_posix()
                zf.write(p, rel)
                files.append({"path": rel, "sha256": sha(p)})
    return base64.b64encode(buf.getvalue()).decode("ascii"), files


def kid(acc, tag):
    return "%s/cbs-sdpoint-%s-%s" % (env_for(acc)[1], tag, acc.lower())


def push(accounts, tag):
    b64, files = payload()
    for acc in accounts:
        setting, seeds = MX.SHARDS[acc]
        env, user = env_for(acc)
        d = STAGE / ("kernel_%s_%s" % (tag, acc))
        d.mkdir(parents=True, exist_ok=True)
        extra = '["--pilot"]' if tag == "pilot" else "[]"
        (d / "script.py").write_text(WRAPPER.format(payload=b64, setting=setting, seeds=json.dumps([str(s) for s in seeds]), extra=extra), encoding="utf-8")
        (d / "kernel-metadata.json").write_text(json.dumps({
            "id": kid(acc, tag), "title": "cbs-sdpoint-%s-%s" % (tag, acc.lower()), "code_file": "script.py",
            "language": "python", "kernel_type": "script", "is_private": True, "enable_gpu": True,
            "enable_internet": False, "enable_tpu": False, "machine_shape": "NvidiaTeslaT4",
            "dataset_sources": ["pankrzysiu/cifar10-python", "%s/%s" % (user, SLUG)],
            "kernel_sources": [], "competition_sources": []}, indent=2))
        RAW.mkdir(parents=True, exist_ok=True)
        (RAW / ("launch_%s_%s.json" % (tag, acc))).write_text(json.dumps({
            "account": acc, "kernel": kid(acc, tag), "setting": setting, "seeds": list(seeds), "tag": tag,
            "launched_utc": datetime.now(timezone.utc).isoformat(),
            "script_sha256": sha(d / "script.py"), "payload_files": files}, indent=1))
        if run(["kaggle", "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], env).returncode:
            raise SystemExit("push failed for %s" % acc)


def verify(acc, tag):
    root = RAW / tag / acc / "cmp"
    rep = {"account": acc, "tag": tag}
    m = root / "MANIFEST.json"
    if not m.exists():
        rep["manifest"] = "MISSING"
    else:
        listed = json.loads(m.read_text())
        missing = [r for r in listed if not (root / r).exists()]
        bad = [r for r in listed if (root / r).exists() and sha(root / r) != listed[r]["sha256"]]
        rep["manifest"] = {"listed": len(listed), "missing": missing, "hash_mismatch": bad}
    for f in ("environment.json", "COMPLETE.json", "inputs_check.json", "job_timing.json"):
        rep[f] = json.loads((root / f).read_text()) if (root / f).exists() else "MISSING"
    (RAW / ("verify_%s_%s.json" % (tag, acc))).write_text(json.dumps(rep, indent=1))
    print(json.dumps({k: rep[k] for k in ("account", "manifest", "COMPLETE.json")}, indent=1)[:1500])
    return rep


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=("publish", "push", "status", "pull", "verify"))
    ap.add_argument("--tag", default="main")
    ap.add_argument("--accounts", nargs="*", default=list(MX.SHARDS))
    a = ap.parse_args()
    if a.action == "publish":
        publish(a.accounts)
    elif a.action == "push":
        push(a.accounts, a.tag)
    elif a.action == "status":
        for acc in a.accounts:
            run(["kaggle", "kernels", "status", kid(acc, a.tag)], env_for(acc)[0])
    elif a.action == "pull":
        for acc in a.accounts:
            dest = RAW / a.tag / acc
            dest.mkdir(parents=True, exist_ok=True)
            run(["kaggle", "kernels", "output", kid(acc, a.tag), "-p", str(dest), "-o"], env_for(acc)[0])
    else:
        for acc in a.accounts:
            verify(acc, a.tag)


if __name__ == "__main__":
    main()
